### ISSUE TITLE
Upgrades not available for production

### ISSUE THREAD

**Issue by MagaTailor** [freeorion/freeorion#1059]
It seems weapon upgrades do not become available upon finishing research and remain stuck at Lvl1. (FO 0.4.6, latest git source, 32-bit ARM Linux)

I played FO 0.4.5 roughly a year ago and the upgrades used to appear immediately.

**Comment by Vezzra** [comment]
Weapon upgrade mechanics have been significantly changed in 0.4.6. Instead of providing new weapon parts with increased stats, the refinement techs increase the stats of the weapon parts unlocked by the base weapon part tech (Mass Driver, Laser, etc.) on all your ships.

This way the already existing weapon parts are "upgraded". The only condition is that a ship has to be within supply to receive the boost. You only need to make a new design if you research a new weapon type (because that will give you a new weapon part).

Which means what you're observing is intended behaviour.

Everything clear now, otherwise feel free to ask for further clarifications 😃

**Comment by MagaTailor** [comment]
I suspected that much but couldn't see any updated weapon labels and didn't notice the stats were improving indeed.

Which makes this bug report real after all - if you click on a weapon type in the design window or do a mouse-over, it shows just the base level/stat, instead of the current one. (pedia affected as well)

**Comment by Vezzra** [comment]
That's because the pedia doesn't (and can't) take into account effects acting on universe objects, because if only looking at the stats of a ship part there is no universe object the effects modifiying the weapon part stats could act on.

Unless you look at the weapon part stats of an actual ship, then of course you get the modified stats, as now you have an actual universe object (the ship) the effects act on.

That you can see modified stats on the design screen for the design currently being created/edited is made possible by creating a temporary ship in the background. AFAIK there is no easy way to do the same for single parts in the pedia, so that's kind of an issue we have to live with... anyone correct me if I got that wrong.

For that reason there is really no point to keep an issue open for that. Unless we redesign the entire effects system I guess we can't really fix this...

**Comment by MagaTailor** [comment]
Right, I love the uncluttered look but don't see why weapons shouldn't show their current level/power which could then link to the corresponding pedia entry (there's always just one item nowadays, i.e the highest attained level).

If you can't choose a lower power part for cost/production speed reasons and there's a single icon at any moment, it really begs to get fixed :)

**Comment by Vezzra** [comment]
The problem is not that there is no good reason to show the modified stats, the problem is the underlying implementation. I expect the changes to actually fix that properly to be very difficult, as you'd need to fix it on the design level. That's a awful lot of trouble... but we probably need a comment of someone more knowledgeable about the code in question than me.

Anyone?
