### ISSUE TITLE
Sidepanel Flicker During turn Updates

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1093]
In the latest master, during turn updates, the contents of the sidepanel flicker visible and not a few times. It's rather distracting. Attached is a composition of screenshots attempting to illustrate the two things that appear and disappear...

The layout also seems to be reset a few times, with the meter bars flickering a bit longer / shorter.

![sidepanel flicker](https://cloud.githubusercontent.com/assets/11386908/20137327/0dacfae2-a67a-11e6-997a-6efa184ce632.png)

**Comment by LGM-Doyle** [comment]
I have replicated this problem and I will work on a solution.

**Comment by MatGB** [comment]
A solution: force close sidepanels and fleet windows at the end of a turn. Having either or both open slows the game down a fair bit for a lot of players, I'd personally prefer it if they auto closed.

**Comment by LGM-Doyle** [comment]
The intent of my post was just to forestall Geoff pinging me to look at this issue.

I play with side panel and the fleet window open, but the objects window closed.  I think I would be unhappy if  they closed each turn, since sometimes I watch my colonies grow.

The slow down can be mitigated.  

The current glitch is due to work to speed up the side panel that has created a mismatch in the redraw timing of the planet container and the side panel proper.  I can fix the glitch.

**Comment by Vezzra** [comment]
According to the discussion @geoffthemedio and @LGM-Doyle had in #1154, this issue has been (almost) completely resolved,  except for this small thing @geoffthemedio mentioned that apparently still lingers:

> There's no visible jitter in the position of the sidepanel controls, but the stealth stat icon does seem to flicker (go black) briefly - perhaps a frame - when pressing turn. (In the case where all the sub-panels are collapsed)

Is that minor enough so we can close this nonetheless, or do you guys want to keep it open until this last bit has been addressed?

**Comment by LGM-Doyle** [comment]
Keep it open or start a new issue with only the remaining issue, so that it is not lost.  The latter would be preferable so that someone can come along and understand the issue without reading the whole thread.

**Comment by Vezzra** [comment]
Ok, done: #1177
