### ISSUE TITLE
Crash in multiplayer

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1194]
Version: g158869b31

Not sure what I did. Core dump: http://dump.bitcheese.net/files/morunuw/core.mp.gz

**Comment by Vezzra** [comment]
Please also state your platform/OS version with each report. Sorry, but I'm getting too old to remember everyone's platform here 😉 

Assuming you're on Windows, I'm surprised you can launch FO at all. I can build current master, but FO crashes immediately on launch. I'm still trying to track down the cause, so far it seems the commit that introduced the issue is f6038bb5ee896795ac9fb126637aa7ed9ad52001.

As that's *before* the commit you referenced (158869b31569f59a7be854afcfcdd0e28cc9bbee), I'd expect you to have the same problem, not only an issue with multiplayer.

However, you didn't provide a more detailed description what happened, and I can't use the core dump provided - on my system that's a file with some binary content I can't decipher.

A backtrace in text format would probably be more helpful, but at least give us a short description where/when, and what exactly happens when you encounter the issue.

**Comment by Voker57** [comment]
linux, debian unstable, right, i already understood that core dump is useless, will try to extract backtrace

**Comment by Vezzra** [comment]
Ah, ok, then your bug is most likely completely unrelated to what I ran into (which is windows specific as far as I can tell so far).

Still, a short description about *what* exactly happens (crash to desktop, freeze, etc.?), *when* (at program launch, in the multiplayer lobby, etc.?), and steps how to reproduce (if possible) would be appreciated (in addition to the backtrace). 😃

**Comment by Vezzra** [comment]
@Voker57, any updates on this? Do you think you can provide a backtrace? And also my other points: a more precise description of what exactly happened and when, also how to reproduce if possible.

If you can't provide any more detailed information, we'll have to close this as invalid, because "Crash in multiplayer" certainly isn't sufficient for us to be able to do anything...

**Comment by Voker57** [comment]
No, I guess this can be closed, backtrace is lost forever. Had no crashes in MP recently either, only in lobby.
