### ISSUE TITLE
Compile errors in AIInterface.cpp and AIWrapper.cpp on OSX

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1228]
### Environment

* **FreeOrion Version**: 4ba51dcaa9cce1148bb2704ef324a97dce43e2d2
* **Operating System**: OSX
* **Fetched as**
  * Compiled from source

### Description

When trying to build FO, AIInterface.cpp and AIWrapper.cpp fail to compile, both with the same set of compile errors.

Build log (for AIInterface.cpp): [buildlog.txt.zip](https://github.com/freeorion/freeorion/files/716144/buildlog.txt.zip)

**Comment by Vezzra** [comment]
Further investigation revealed 4ba51dcaa9cce1148bb2704ef324a97dce43e2d2 being the commit introducing the issue. @LGM-Doyle, that's one of yours.

Also, the issue *only* occurs on OSX. On Linux and Windows I can build FO just fine.

OP updated accordingly.

**Comment by LGM-Doyle** [comment]
@Vezzra, I've looked at the log file and I don't immediately know what the fix is.

The issue is a known issue, see https://bugs.python.org/issue10910

I think that the  `#include <boost/python/str.hpp>` is triggering the problem.

Could you check what versions of boost and python that you are using on all 3 machines?

Could you also try https://github.com/LGM-Doyle/freeorion/tree/fix_1228_boost_python_OSX_wont_compile to see if it fixes the problem?

**Comment by Vezzra** [comment]
> I think that the #include <boost/python/str.hpp> is triggering the problem.

That's my guess too.

> Could you check what versions of boost and python that you are using on all 3 machines?

Windows: Boost 1.59, Python 2.7.12
OSX: Boost 1.59, Python 2.7.10
Linux: Boost 1.58, Python 2.7.12

> Could you also try https://github.com/LGM-Doyle/freeorion/tree/fix_1228_boost_python_OSX_wont_compile to see if it fixes the problem?

Nope, doesn't change anything. Still get the same compile errors.

**Comment by geoffthemedio** [comment]
Try putting ````#include <boost/python.hpp>```` before the str.hpp include?

**Comment by LGM-Doyle** [comment]
Thanks for answering the questions and trying yesterday's fix.

I was hoping that perhaps your OSX machine was using an older Boost version.  

I don't think that the python version is significant, because I think the compile fails before it looks at anything python, but now that I've written it, it will turn out to be the only information that is significant.

Could you try todays attempted fix https://github.com/LGM-Doyle/freeorion/tree/fix_1228_boost_python_OSX_wont_compile2

**Comment by Vezzra** [comment]
> Try putting #include <boost/python.hpp> before the str.hpp include?

That too didn't help.

> Could you try todays attempted fix https://github.com/LGM-Doyle/freeorion/tree/fix_1228_boost_python_OSX_wont_compile2

Yep, that did the trick. Went ahead and merged your branch into master. Thanks for the fix! 😃

Closing as fixed by b6126e90ec1fe3c925ae1642bc4cca7da67f7130.
