### ISSUE TITLE
Failed to load texture of shadowed planet when started from shell

### ISSUE THREAD

**Issue by maldag** [freeorion/freeorion#1258]
When started from bash console without cd to the compiled project, the texture for a shadowed planet is not loaded and replaced by a blue circle in the galaxy map.
I've compiled from source with git hash c36bb67

Linux: Mint 18.1, x64,
`uname -a
Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`> ~ $ source/freeorion/freeorion &
[1] 2345
> ~ $ Texture::Load passed non-existant path: default/data/art/icons/unknown.png
FreeOrion server waiting for network events`

When I move into the folder 'source/freeorion/freeorion' and start from there by './freeorion &' it works perfectly.

**Comment by dbenage-cx** [comment]
`Texture::Load passed non-existant path: default/data/art/icons/unknown.png` is related to cc63dca.

When compiling from source, it is intended for the game to be run from a parent directory of `default/`.
This is accomplished by either launching from the source directory or providing a symbolic link (see http://freeorion.org/index.php/Compile_In_Linux#Compiling_FreeOrion).
Since that is the root of the issue here, marking this as `Invalid`, but this issue resulted in some related minor fixes.
