### ISSUE TITLE
AI greeting message is corrupted.

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#1264]
`v0.4.6+ [build 2017-01-31.e5a110e] MSVC 2015` Win7 64

- start new game
- check AI greetings in the message window

```
AI_1: County (): Worthless insects, you dare to challenge our mighty empire?!
AI_2: Segment (): Worthless insects, you dare to challenge our mighty empire?!
AI_3: Command (): Despair and defeat is what you're going to find at our hands.
AI_4: Sept (): Worthless insects, you dare to challenge our mighty empire?!
```

python code responsible for that:   `default/python/AI/FreeOrionAI.py:222`
```python
fo.sendChatMessage(human_player, '%s ([[%s]]): [[%s]]' % (empire.name, get_trait_name_aggression(foAIstate.character), greet))
```

I think it is trouble in chat tags been parsed. If I input  `hello ([[aa]]) [[bb]]` to chat I will get:
```
@: hello  ():  zzz
@: hello () 
```

**Comment by Dilvish-fo** [comment]
CJ, if I type 
```hello([[GSETUP_BEGINNER]]) :zzz```
into the chat window, then I get back just fine: 
```Dilvish: hello(Beginner Mode) :zzz```

Worked fine for Maniacal also (didn't test the others).   Doing a little fiddling, it looks like get_trait_name_aggression(foAIstate.character) is doing the translation itself, rather than returning a stringtable label, and so just changing the cited FreeOrionAI.py line to 
```python
fo.sendChatMessage(human_player, '%s (%s): [[%s]]' % (empire.name, get_trait_name_aggression(foAIstate.character), greet))
```
fixes the problem.  Since the comment for get_trait_name_aggression  is "# Human readable trait name functions for debugging" it seems it is performing as intended, and so the change I propose above seems to be the correct one, and I will probably go ahead and put it in.

**Comment by LGM-Doyle** [comment]
@Dilvish-fo thanks for fixing my mistake.  I didn't realize that my addition of Character has broken chat.
