### ISSUE TITLE
Turn start messages contains duplicated entries.

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#1295]
Chat message that shown between turns looks confusing.   There is two `Downloading and Unpacking New Game-state`
```
Saving...
Saved 189878 bytes to file: C:\Users\sa\AppData\Roaming\FreeOrion\save\auto\FreeOrion___0003_20170208_233302.sav
Waiting for Other Players
Executing Orders
Colonization, Invasion, and Scrapping
Fleet Movement
Downloading and Unpacking New Game-state
Resolving Combat
Production and Growth
Downloading and Unpacking New Game-state
Begin Turn 4
```

As I see in code this is two different actions with same message:
```c++
 // indicate that the clients are waiting for their new Universes
m_networking.SendMessage(TurnProgressMessage(Message::DOWNLOADING));
```

```c++
// indicate that the clients are waiting for their new gamestate
m_networking.SendMessage(TurnProgressMessage(Message::DOWNLOADING));
```

Looks like need to: 
- add DOWNLOADING_UNIVERSE  to TurnProgressPhase
- case to MessageWnd::HandleTurnPhaseUpdate
- entries to translation tables

`v0.4.6+ [build 2017-01-31.e5a110e] MSVC 2015`

**Comment by geoffthemedio** [comment]
Saying explicitly "Downloading Universe" for the mid-turn update, and then not explicitly saying it for the full turn update would be misleading, as a universe update happens in both cases. The repeated message is accurate...

**Comment by Dilvish-fo** [comment]
I would agree with Geoff that the repeated message is accurate and seems fine to me.

The alternative would be for the two messages to be somewhat more specific and therefore not repeated.  Instead of using the single Message::DOWNLOADING for both of the situations noted by CJ, we could use a Message::PRECOMBAT_DOWNLOADING and a Message::POST_COMBAT_DOWNLOADING, so that CJs example could read (in the English version)
```
Saving...
Saved 189878 bytes to file: C:\Users\sa\AppData\Roaming\FreeOrion\save\auto\FreeOrion___0003_20170208_233302.sav
Waiting for Other Players
Executing Orders
Colonization, Invasion, and Scrapping
Fleet Movement
Downloading and Unpacking Pre-Combat Game-state
Resolving Combat
Production and Growth
Downloading and Unpacking Post-Combat Game-state
Begin Turn 4
```

However, stating "Pre-Combat" and "Post-Combat" instead of "New" is really just redundant with the other status lines that are given, and so the small bit of extra explicitness doesn't really seem worth the extra code complication to me.

**Comment by Vezzra** [comment]
I don't have a strong preference here, and no actual objection to make two different, more specific messages. However, I basically agree with @geoffthemedio and @Dilvish-fo, I don't think that's really necessary.

**Comment by Dilvish-fo** [comment]
Seems to me we should close this, as either invalid or won't-fix.

**Comment by Vezzra** [comment]
I'd suggest closing as invalid.

**Comment by Vezzra** [comment]
Oops, apparently this got completely forgotten. Anyway, no one has objected against closing this as invalid, so I'm going to do that now.
