### ISSUE TITLE
Improve combat logs wrt Fighters

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1325]
First suggested by UrshMost and Oond in [this forum thread](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10339#p86779)

> In the Combat Report Log file it would make more sense if carriers were shown launching fighters before they are shown being destroyed.

> When you're in a battle with a few hundred fighters on each side, the combat log becomes mostly unreadable with "fighter attacks fighter" taking up most of the space.

(milestone 0.4.7 due to "polish fighters" guideline)

**Comment by LGM-Doyle** [comment]
The first issue was fixed in [Move combat log launch events before destroy events in bout_event. ](https://github.com/freeorion/freeorion/commit/f2f78cdc96e779e514e60fc6817799c102388875)

PR #1334 tries to address the second issue.

**Comment by Vezzra** [comment]
@dbenage-cx, @LGM-Doyle, with both issues addressed, can we close this issue? Or shall we wait for #1355 to be merged too, as it kind of also addressed the general intend of this issue (improving the combat log wrt to fighters)?

**Comment by LGM-Doyle** [comment]
I'd either: 
- close the issue, since this issue is dealt with and then open new issues for subsequent combat log changes.  #1355 was a change based on a request within the previous PR.  

- Or modify the initial post to have a checklist so that people don't have to read through the body of the post to determine if extra requests have expanded the scope of the issue.

**Comment by Vezzra** [comment]
Prefer the first option 😃

Fixed by f2f78cdc96e779e514e60fc6817799c102388875 and #1334.
