### ISSUE TITLE
Colonize button doesn't render properly after cancellation

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1363]
### Environment

* **FreeOrion Version**: #1355 rebased onto 6677899
* **Operating System**: Linux
  * Compiled from source

### Description
When cancelling a colonisation, the button on *other* planets on the same system doesn't render correctly if the system has been deselected and then reselected after selecting a colonisation target.

### Expected Result
All planets should have properly rendered button.

### Steps to reproduce
Send outpost or colony ship to a system with at least two valid targets. Select one, close sidepanel, reopen sidepanel, cancel colonisation
![screenshot_20170223_155110](https://cloud.githubusercontent.com/assets/11533206/23267409/99057766-f9e2-11e6-95e7-5a627b8e58df.png)
![screenshot_20170223_155123](https://cloud.githubusercontent.com/assets/11533206/23267410/99180dfe-f9e2-11e6-8ef0-b7e81ca6ed6e.png)
![screenshot_20170223_155052](https://cloud.githubusercontent.com/assets/11533206/23267408/98f0cf50-f9e2-11e6-9bcd-650d84e4c6fd.png)

**Comment by dbenage-cx** [comment]
@LGM-Doyle Would it be highly detrimental to require prerender for child windows?
e.g.
```
diff --git a/GG/src/Wnd.cpp b/GG/src/Wnd.cpp
index 69b8dcf..e0f516b 100644
--- a/GG/src/Wnd.cpp
+++ b/GG/src/Wnd.cpp
@@ -861,7 +861,11 @@ void Wnd::PreRender()
 }
 
 void Wnd::RequirePreRender()
-{ m_needs_prerender = true; }
+{
+    for (auto& child_wnd : m_children)
+        child_wnd->RequirePreRender();
+    m_needs_prerender = true;
+}
```

**Comment by LGM-Doyle** [comment]
Yes it would be detrimental.

The performance improvements for the ListBox windows, FleetWnd, ObjectsWnd, SaveDialog come from not prerendering the fleets, ships, objects and saves that are not visible, not changed or do not need a prerender, which are most of the child windows and most of the time.  Most of the work is unnecessary.

It is the same with the SidePanel and its many,  although more varied child windows.  

PreRender is an opt-in technique.  Once a top-level window chooses to PreRender, it is responsible for managing its children.


The underlying problem is that not all of GG is prerender aware and much of the UI expects all changes to be immediate.  If everything only expected sizing to change once per render interval, it would all work.  If everything changes immediately, it also works, but is slower.


In this particular case, the problem seems to be that the colonize, invade and bombard buttons are detached and then not reattached.

In SidePanel.cpp near https://github.com/freeorion/freeorion/blob/master/UI/SidePanel.cpp#L1672 in `PlanetPanel::Refresh()`, they are all detached.
````
    DetachChild(m_invade_button);
    DetachChild(m_colonize_button);
    DetachChild(m_bombard_button);
````
and then conditionally attached:
````
   if (can_colonize) {
        AttachChild(m_colonize_button);
        ... removed some code here
    } else if (being_colonized) {
        // shown colonize cancel button
        AttachChild(m_colonize_button);
        ... removed more code here
    }
````
There is similar code for the other two buttons.

If the planet is not currently being colonized or a colonization possibility, then the colonize button is not re-attached.

Then later in time, but earlier in the file near https://github.com/freeorion/freeorion/blob/master/UI/SidePanel.cpp#L1034, in `PlanetPanel::DoLayout()`
````
    if (m_colonize_button && m_colonize_button->Parent() == this) {
        m_colonize_button->MoveTo(GG::Pt(left, y));
        m_colonize_button->Resize(GG::Pt(GG::X(ClientUI::Pts()*15), m_colonize_button->MinUsableSize().y));
        y += m_colonize_button->Height() + EDGE_PAD;
}
````
the button is placed conditional on being attached.  If it is detached, then it is not placed.  

When it toggles state it is not being re-attached, or placed so it shows at (0,0) for its parent.

Fixes that I would try:
- Put `RequirePreRender();` in `PlanetPanel::Refresh()`.  Conditionally, when something changes would be best, but the code look hairy, so we could try unconditional and then fix any slow downs that occur later.
- Don't detach the button. Hide/show it as appropriate.  Change the placement logic to not shift subsequent rows down if this button is hidden.  Check that planets that can be bombarded and invaded still display correctly.

I hope that this helps.

**Comment by geoffthemedio** [comment]
> Don't detach the button. Hide/show it as appropriate.

I think that a parent being hidden / shown will hide / show its children automatically, but not any non-child members.

**Comment by dbenage-cx** [comment]
TY for the detailed answer, will work on a fix.
