### ISSUE TITLE
Dragon Tooth weapons have 0 strength.

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1386]
### Environment
* **FreeOrion Version**: 0.4.6+
* **Operating System**: Fedora 25
* **Graphic card used**: N/A
* **Fetched as** 
  * Compiled from source cf67d52

### Description
When awarded a Dragon Tooth from an Ancient Ruins, the ship has a total weapon capacity of 0.

Seen with empires without Death Ray researched, possibly due to the change in default weapon effects.

**Comment by Vezzra** [comment]
"component:art music text assets" does not really fit here... that applies primarily to text e.g. in the pedia, and sound and graphics files.

This issue here clearly is a bug in the content scripts.

**Comment by geoffthemedio** [comment]
To resolve, could replace the dragon tooth design's `SR_WEAPON_4_1` with something special, which doesn't depend on a tech for its power.

**Comment by MatGB** [comment]
I'd be cautious about doing that as the Tooth itself is unlocked to be built when you get one, so if you research all the techs you can then build more: that currently you wouldn't bother as the top end Core fuel generator is a bit of a waste isn't to say that at some point we'll do enough work to fix that issue. Plus, that the Death Ray now gets the refinements put Teeth back into the "not a bad result" category for the mid to late game, if that's removed they'll go back to "scrap instantly" for players watching upkeep and beyond DR1 in tech.

A different, equally non-optimal approach is to have the DT unlock Death Rays as well, but I don't think that's ideal.  Having the DT only unlock if you've already got DRs (eg through a previous Ruin) would work as could hard coding something into the Hull script that triggers if the owner hasn't got the tech.

I think the last is the least awful solution of those I can think of.

**Comment by Dilvish-fo** [comment]
Rather than having the DT unlock the regular Death Ray techs, it could unlock a specialized, non-researchable DragonTooth tech which applies the same effects as the Death Ray techs, but only to a Dragon Tooth ship (and only if you don't also have the Death Ray techs, to avoid doubling up).  You'd still need the DR tech to actually build a DT, but the DT you got from the ruins should work fine.

**Comment by dbenage-cx** [comment]
A tech or effect sounds good and seems this is only due to the secondary stat meter being 0.
I tried the following for an initial pass (`default/scripting/ship_hulls/SH_XENTRONIUM.focs.txt`):
```
EffectsGroup
    scope = Source
    activation = And [
        Not OwnerHasTech name = "SHP_WEAPON_4_1"
        DesignHasPart low = 1 name = "SR_WEAPON_4_1"
    ]
    effects = [
        SetMaxSecondaryStat partname = "SR_WEAPON_4_1" value = max(Value, 1.0)
        SetSecondaryStat partname = "SR_WEAPON_4_1" value = max(Value, 1.0)
    ]
```
A suggestion that may need to spawn into a forum post: cover this issue and increasing the desirability of the hull with an increased secondary stat (and a malus to capacity).
e.g for death ray:
`SetMaxSecondaryStat partname = "SR_WEAPON_4_1" value = Value + max(1, Value * 0.5)`
`SetMaxCapacity partname = "SR_WEAPON_4_1" value = Value * 0.6`

**Comment by MatGB** [comment]
I like that idea but it'd be a change rather than a bugfix so would need some testing: increasing the ROF for an unusual hull would be a good way to expand the mechanic in the first instance but it'd need AI adjustment as well.

And it makes sense that the problem is the ROF isn't being set properly, good catch.

**Comment by l29ah** [comment]
Too bad the Dragon Tooth is of questionable use given you were able to beat the ruin guardian wielding 800 armor and a death ray.

**Comment by Vezzra** [comment]
Considering the issues introduced and what strikes me as complicated workarounds to fix those issues I'm starting to second guess the idea of moving the effects which set the damage stat of weapons from the parts themselves to the techs.

If I understand correctly there seem to be some performance gains, but apparently we kind of opened a can of worms here. The underlying problem of all these issues seem to be caused by the fact that effects attached to techs don't apply at all to unowned ships, and also not to ships that one way or the other end up in possession of an empire that hasn't the techs for the weapon parts on that ship.

Which means we need to add additional effects elsewhere which take care of these cases, making the scripting of a weapon part complicated, confusing and prone to error (because whenever you want to tweak something, you must not forget to account for all the other places where bits of the scripting for that part are scattered).

How noticeable are the performance gains?

**Comment by MatGB** [comment]
The key move was taking the bonuses out of Species, whether it's in techs or parts shouldn't make that big a difference: because we've done a fair bit of other performance gain work recently *and* I kept forget to compile from that branch to test it explicitly I didn't personally notice a difference for this change, but there have been substantial improvements overall in this cycle.

**Comment by Vezzra** [comment]
Ah, ok, I understand - when those effects have been attached to species, there has been no problem because every ship has a species, owned or not. But when the effects have been moved into the techs, that became a problem.

So wouldn't moving all the effects determining the damage stats of wepon parts to the actual parts be the better approach...?

**Comment by geoffthemedio** [comment]
My theory is/was that weapon-modifying effects are better put in techs (than parts, and especially species) if possible because that would involve a single multi-target effect scope evaluation and execution, rather than many single-target evaluations and executions. There were no actual benefits in the test that (I think) @LGM-Doyle ran, though his test case involved relatively small numbers of objects in the Universe.

It might help more if there were activation conditions for tech effects that apply to weapon meters, so that if there is a higher-level version of the tech (an upgrade) researched, only that single effect is applied, rather than separate effects for the base weapon tech and each upgrade tech.
