### ISSUE TITLE
Save Overwrite Confirm Layout Quirk

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1407]
See screenshot, produced when trying to save over an existing file.
![save_confirm_layout_qurik](https://cloud.githubusercontent.com/assets/11386908/24054125/65e5671e-0b3b-11e7-9c45-71dcdb366048.png)

**Comment by Dilvish-fo** [comment]
For me, the word 'override' appears at the end of the first line, and everything fits fine.  So that suggests that the issue relates to the box being a fixed size and not checking how many lines the text requires to display (if you've changed font size).  Still, just making the box a bit taller so it can accommodate two lines before the filename seems like the simplest reasonable fix.

**Comment by Vezzra** [comment]
And make it a bit wider to ensure "override" stays on the first line on all platforms.

**Comment by adrianbroher** [comment]
FYI: This is not reproducible on Linux.  Also this issue was presumably reported on Windows with freetype 2.5.5 as dependency, which is quite old.  With the new v10 SDK this issue should be gone.

Can you please recheck if it is fixed now @geoffthemedio ?

**Comment by adrianbroher** [comment]
I'm currently refactoring the usage of the `GG::ThreeButtonDlg` and I'm unable to get to see the one related to the `Concede` button as this feature is disabled? Tried multiplayer with a single and multiple clients.

**Comment by geoffthemedio** [comment]
Re: this issue, the prompt text has changed to be shorter, so I suppose the issue is resolved, but that doesn't indicate anything about whether a freetype update would have or has had an impact.
