### ISSUE TITLE
Let colony-less races build outposts and drydocks

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1410]
Since outposts are not really colonies, non-colonized races should be able to build them and to build dry-docks to repair ships. Not having this possibility adds tedium to the game. Story-wise, they can borrow outpost personnel and ship crew from other visiting races.

**Comment by Dilvish-fo** [comment]
It seems to me like what is described here is neither a bug nor a feature request, but (to the extent it does not simply seem inaccurate) it seems like it is simply asking to change current design choices, which to my understanding is to be done in discussions on our forums (and this PR should be closed as invalid, I think).  I'll hold off on actually closing this issue myself and marking it as invalid, though, since I am still getting up to speed on the github guidelines that were adopted while I was inactive.

The part that seems inaccurate is the part about drydocks.  Building drydocks is tied to shipbuilding and is not gated by whether or not a species can colonize.  And if a species can't build ships I doubt we'll let them repair them, but you could ask about that on the forum.  It kind of sounds like maybe you want all species to be able to build ships (because that's how all outposts are made), but please just clarify on the forums rather than here.

**Comment by Vezzra** [comment]
Well, this isn't a PR... anyway, I agree. It's more a request to reconsider certain design choices, and our issue tracker isn't really the place to discuss something like this. So I also vote for closing this as invalid.

@Voker57, please open a thread about your suggestion on the forum.
