### ISSUE TITLE
FreeOrion executable dependency on missing DLL

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1426]
### Environment

* **FreeOrion Version**: 60b8488aa44d68d706161a2d10b8b39ecdf817c0
* **Operating System**: Windows
* **Fetched as**
  * Compiled from source

### Description

When installing FO from the installer package which has been created by the NSIS installer script, the following error message pops up when trying to launch the application:

![fehlermeldung](https://cloud.githubusercontent.com/assets/10279417/24169011/8c1209ee-0e7c-11e7-9b57-fe845c76a5e8.png)

This basically says that the application can't be run because "boost_chrono_vc140-mt-1_59.dll" can't be found.

I guess something has been left over in the MSVC project when boost chrono has been removed, which causes the FO executable still to be linked against `boost_chrono_vc140-mt-1_59.dll`.

### Steps to reproduce

* Build FO on Windows with the SDK.
* Run the NSIS installer script to create the installer package.
* Install FO with the created installer on a different Windows system.
* Try to run FO there.

**Comment by geoffthemedio** [comment]
Based on loading freeorion.exe in Dependency Walker, boost threads and boost log have dependencies on boost chrono.

**Comment by adrianbroher** [comment]
> I guess something has been left over in the MSVC project when boost chrono has been removed, which causes the FO executable still to be linked against boost_chrono_vc140-mt-1_59.dll.

It's caused by #1420. Seems like boost thread does have a [`BOOST_THREAD_DONT_USE_CHRONO`][1] configuration define so a new version of the FreeOrionSDK needs to be build to have a boost chrono free variant of boost thread.  Of course the easy and cheap way to fix this is to re-add `boost_chrono` to `cmake/make_versioncpp.py`.

> Based on loading freeorion.exe in Dependency Walker, boost threads and boost log have dependencies on boost chrono.

I'm not sure about the boost log dependencies.  According to the [documentation][2] it should not be there. Maybe it's an indirect dependency because boost log depends on boost thread too.


[1]: http://www.boost.org/doc/libs/1_59_0/doc/html/thread/build.html#thread.build.configuration.chrono
[2]: http://www.boost.org/doc/libs/1_59_0/libs/log/doc/html/log/installation/config.html

**Comment by adrianbroher** [comment]
Looking into the boost thread code it's probably better to readd boost_chrono to `cmake/make_versioncpp.py` until boost thread is replaced with the c++11 thread as adding the `BOOST_THREAD_DONT_USE_CHRONO` seems to disable some functions of boost thread and is intended to be used for compilers incompatible with boost chrono rather than to use c++11 chrono.

**Comment by LGM-Doyle** [comment]
Are we using `boost::thread` for a reason?  

Besides makefiles and projects there only seem to be 3 mentions of it in the code.

@adrianbroher ,  would you like me to make an issue and try to remove `boost::thread` as a dependency? Or not?

**Comment by adrianbroher** [comment]
> @adrianbroher , would you like me to make an issue and try to remove boost::thread as a dependency? Or not?

Feel free to do so, but this won't remove the internal dependencies between the boost libs.

**Comment by Vezzra** [comment]
> Are we using `boost::thread` for a reason?

Effects processing is done using multiple threads, I guess `boost::thread` is used for that...?

**Comment by o01eg** [comment]
What if move it to `std::thread`?

**Comment by Vezzra** [comment]
That's what @adrianbroher suggested, and is the long term plan (if I understand correctly). Once that's done, the dependency on `boost::thread` can be removed.

**Comment by LGM-Doyle** [comment]
@Vezzra, they are used in the effects processing, but also in the networking code, the timers and delays.

Both `boost::thread` and `std::thread` handle the creation and transferring of data to threads provided by the OS.  

The `std::thread` feature set increases in C++14 and C++17 with a variety of shared mutexes.  However, `boost::thread` has a much larger set of synchronization primitives, as it acts as a proving ground for future std features.  We do not directly depend on any of these additional features, but some of the other boost dependencies do.  These are the "internal dependencies" that @adrianbroher  is referring to.

**Comment by Vezzra** [comment]
Ok, I see. Well, sounds like we've to keep `boost::thread` around for the time being.
