### ISSUE TITLE
Please use JavaScript for scripting

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1433]
Current scripting engine (idk what is it, python?) is horribly inconvenient and limited.
There already is v8 library that is stable, fast and easy to integrate.
Javascript allows to implement complex logic easily and is readable. Python is, ugh, language for learning programming basics maybe.
Why was it chosen at all?

**Comment by adrianbroher** [comment]
> Javascript

Go away.

**Comment by Vezzra** [comment]
> Current scripting engine (idk what is it, python?) is horribly inconvenient and limited.

How so?

> There already is v8 library that is stable, fast and easy to integrate.
> Javascript allows to implement complex logic easily and is readable.

The same applies to Python. Probably even more so.

> Python is, ugh, language for learning programming basics maybe.

If you think that, you obviously don't know anything about Python. It's very popular, and e.g. big open source applications like Gimp and Blender use it as scripting language too. I wonder why...?

> Why was it chosen at all?

I haven't been around when that decision has been made, that was long before I joined. But I guess because it's a popular scripting language, easy to learn, very readable, fast, stable, has an extensive standard library, and with `boost::python` it is quite easy to embed in an application.

I like Python very much. But of course that's also a matter of taste, and not everyone will like Python, some might prefer something else. There have been suggestions to use LUA as scripting language for FO, for example.

However, you have to make a decision, and for FO this decision has been Python. We're not going to revise that decision (unless we run into some shortcomings of Python that force us to, which is extremely unlikely). Satisfying some personal preferences does not justify the effort required to reimplement the interfaces and all the scripts (not that anyone of the team prefers JavaScript to Python anyway, AFAIK). That would be beyond ridiculous.
