### ISSUE TITLE
Server not terminated when client throws from duplicate FOCS name

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1556]
### Environment
* **FreeOrion Version**: 0.4.7+
* **Operating System**: Linux
* **Fetched as** Compiled from source

### Description
When client crashes from a duplicate FOCS definition name, server is left running.
Possibly first reported in https://github.com/freeorion/freeorion/issues/1504#issuecomment-299726646

### Expected Result
All processes terminate.

### Steps to reproduce
* Copy some FOCS definition to a new file
 (`default/scripting/ship_designs/SD_CARRIER.focs.txt`->`default/scripting/ship_designs/SD_CARRIERX.focs.txt`)
* Start client and new game
* Client throws `what():  ERROR: More than one predefined ship design has the name SD_CARRIER`
* `freeoriond` and all `freeorionca` processes are left running

**Comment by LGM-Doyle** [comment]
@dbenage-cx thanks for confirming that it was a different issue and opening this PR.  

I think that the problem was that a duplicate FOCS element caused a crash that created hung processes that persist and prevent startup even after the FOCS elements are fixed.  I've created a PR #1558 to fix that problem.

@johndh, Could try it and see if it fixes your problem?

You will have to kill any running freeorion processes.  Check that 
````pgrep -a freeorion```` 
are all things that you want to kill.  If so, kill them
````pkill -9 freeorion````

Then startup freeorion normally with the #1558, and report back on whether it fixes your issue, or not.

**Comment by johndh** [comment]
I have not encountered this error since the update, so I consider it resolved on my end.
