### ISSUE TITLE
UI shows false mandatory stops on areas discovered from derelict scout

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#1569]
### Environment

* **FreeOrion Version**: 2017-05-09.ab336ed_Test_Win32
* **Operating System**: Windows 7
* **Graphic card used**: Nvidia 660 GTX
* **Fetched as**
  * Binary release
  * Weekly development build

### Description
On an area discovered from a derelict scout, the UI shows mandatory stops on star systems as if they where still unexplored:
![mandatory_stops](https://cloud.githubusercontent.com/assets/28650914/26055575/c89517a6-3971-11e7-9c2e-c643314c36d0.jpg)
The correct stops for that route are shown correctly (the unnecessary stops are cleared out) after next turn.

### Expected Result
The stops labelled 3 and 5 in the image should not be there. That would be the expected stops if the area wasn't discovered. Quoting MatGB: "For some reason the pathfinding algorithm doesn't know that those systems are now known so it wants you to stop at all these 'unknown space' sections".

**Comment by MatGB** [comment]
Related/part of.
![screenshot_20170602_140441](https://cloud.githubusercontent.com/assets/11533206/26726835/771e8d42-479c-11e7-84ee-1477585090b3.png)
The system at Vanant y was hidden and "unexplored region" due to the ion cloud, it moved away so I know I can safely move my destroyer up to take out a dyson forest, but the destroyer is marked as stopping (and will stop at) a now visible system.

Suspect that the timing of effects is after the routefinder mapping, beyond that no clue.
