### ISSUE TITLE
Improve performance for large (5000) system games.

### ISSUE THREAD

**Issue by robinteus** [freeorion/freeorion#1622]
[Feature] Can you "fix" 5000 Systems problems
like The Cpu use
because i like to play big huge map ect if that is possible otherways i request may lower the system limit if this cant be changed

all over the main request is fewer"less" CPU use

BTW more than 5000 Systems COOL 👍

**Comment by LGM-Doyle** [comment]
@robinteus thanks for playing and posting the youtube videos,

Most players choose their number of systems and AIs to work acceptably on their computer.  My machine definitely will not work with anything close to 5000 systems.  The default settings for the game are currently 150 systems and 6 AIs, which runs well on many computers.

Since FreeOrion runs on your computer with 5000 systems, we would appreciate more specific feedback on performance hurdles.  

Programming is all about the details.

If you can describe specific screens, buttons or scenarios that are troublesome, then that will point us in the right direction for future troubleshooting.

Drop by the [forum](http://freeorion.org/forum/viewtopic.php?f=28&t=10550&hilit=performance).  There is even a topic on [5000 system games](http://freeorion.org/forum/viewtopic.php?f=28&t=10550).

**Comment by Vezzra** [comment]
This is more or less a request to improve overall game performance, something that is/has to be worked on continually anyway. Moreover, most likely for as long as this project keeps going, which means we'll never reach a point where we could close such an issue as "resolved".

So I'm not sure if keeping an issue open for that really makes much sense - @geoffthemedio?

**Comment by geoffthemedio** [comment]
agree... too vague to be of much use.

**Comment by Vezzra** [comment]
Closing as invalid for the reasons cited above.
