### ISSUE TITLE
newly created ships are not blockaded

### ISSUE THREAD

**Issue by TheSilentOne1** [freeorion/freeorion#1648]
Reported by Matt here on this PR ( https://github.com/freeorion/freeorion/pull/1616 ).
When a ship is produced in a blockaded system, it should be blockaded as if it had arrived from a starlane.

**Comment by Dilvish-fo** [comment]
I've started looking into this before, but didn't get it resolved.  But I just saw a case where this let an empire wrongly be deemed to have broken a blockade simply because a fleet newly created in the blockaded system survived past its first battle (but without having killed all the previously present enemy warships).  So I will prioritize resolving this.

**Comment by Vezzra** [comment]
Ok, with that observation I think this should now considered a quite serious bug, even if it's very rare. Changing milestone to "v0.4.8 (manadatory)".
