### ISSUE TITLE
Crash When Closing

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1651]
Latest master. Start game, quickstart, wait until turn has finished loading, click top-right X to close window. Get an access violation. Load in debugger, see attached.

![this_was_nullptr](https://user-images.githubusercontent.com/11386908/28922274-bb3dfeca-7859-11e7-9aa6-a5b22f52a4b7.png)

Don't get the error if clicking X before quickstarting.

**Comment by LGM-Doyle** [comment]
I am unable to duplicate this.

However, `WndDying()` does not exist after the conversion to `shared_ptr` #1632, since all of its functionality is encompassed by using shared pointers.  After the conversion is complete this bug will not exist. 

I suggest not fixing it before the conversion and checking that it is fixed after the conversion.

**Comment by geoffthemedio** [comment]
Seems to be resolved.
