### ISSUE TITLE
friend void UniverseObjectDeleter : Unnecessary?

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1669]
https://github.com/freeorion/freeorion/blob/master/universe/UniverseObject.h#L202

In UniverseObject and derived classes (Building, Ship, etc.), there are these template friend declarations for UniverseObjectDeleter. I don't see any other reference to that name, and removing those lines doesn't seem to break anything. Are these lines necessary?

**Comment by LGM-Doyle** [comment]
`UniverseObjectDeleter` was added in b68ad7a0a530a57a4704d08300d360ac40e13d68 when converting from `boost::shared_ptr` to `std::shared_ptr`.  It replaced `boost::checked_delete<T>`, which is a template intended to guarantee the visibility of the destructor of T.  Since `UniverseObjectDeleter` has no body, I don't think it fulfills the same purpose.  I don't know why it was added.

**Comment by adrianbroher** [comment]
The [std::shared_ptr](http://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr) needs access to the destructor of the object it is managing.  At the time the commit LGM-Doyle linked was made the destructors had private visibility and the UniverseObjectDeleter was the implementation of a deleter that can be passed to the std::shared_ptr constructor to allow access to the private destructor.

**Comment by LGM-Doyle** [comment]
Thanks @adrianbroher I missed that it was making the private destructor available.

**Comment by geoffthemedio** [comment]
Removed the declarations in https://github.com/freeorion/freeorion/commit/2e4aebec09ca7f8f92ecbef1c992cd25f948e844
