### ISSUE TITLE
r600g - Starlanes do not render when visiblity radii are enabled

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1674]
### Environment

* **FreeOrion Version**: 0.4.7+
* **Operating System**: Fedora 26
* **Graphic card used**: AMD RV770 
* **Fetched as** * Compiled from source
[glxinfo.txt](https://github.com/freeorion/freeorion/files/1223969/glxinfo.txt)

### Description
On upgrade to Fedora 26, starlanes no longer render when visibility radii are enabled.
While this is likely a driver issue, opening here first as it may indicate some incorrect GL usage/state I have not found.
![default](https://user-images.githubusercontent.com/17205519/29297662-1f0ef5cc-8128-11e7-8cd8-a0bde4f99880.png)

Reordering the render somehow resolves this issue:
```diff
diff --git a/UI/MapWnd.cpp b/UI/MapWnd.cpp
index 225005365..d89ed7065 100644
--- a/UI/MapWnd.cpp
+++ b/UI/MapWnd.cpp
@@ -1710,10 +1710,10 @@ void MapWnd::Render() {
 
     RenderStarfields();
     RenderGalaxyGas();
-    RenderVisibilityRadii();
     RenderFields();
     RenderSystemOverlays();
     RenderStarlanes();
+    RenderVisibilityRadii();
     RenderSystems();
     RenderFleetMovementLines();
 ```
![reordered](https://user-images.githubusercontent.com/17205519/29297671-25ab8224-8128-11e7-91a0-b83e5ab2487d.png)

Running the game using software rendering `LIBGL_ALWAYS_SOFTWARE=ON freeorion` and without the above diff is a temporary workaround.

Traces run using [this branch](https://github.com/freeorion/freeorion/compare/master...dbenage-cx:debug_gl) with `apitrace trace build/freeorion -q --auto-advance-n-turns 3 --auto-quit`.
Branch adds gl debug groups in some MapWnd functions to help parse the trace.  [apitrace repo](https://github.com/apitrace/apitrace/)
[Trace files](http://freeorion.cxdamian.net/apitrace_freeorion.tar.gz) (91MB)

**Comment by Vezzra** [comment]
I assume the issue is for 0.4.6+ because that's the most recent FO release in the Fedora repos?

Anyway, if the fix is that simple (just the reordering of the render calls you suggested above), and it doesn't break anything on any other platform, I'd say go ahead and commit the fix.

This fix would also be a candidate for the bugfix release I guess...?

**Comment by geoffthemedio** [comment]
Changing the rendering order changes the appearance of what is rendered. In this case, the radii would appear over instead of behind fields, overlays, and starlanes.

**Comment by Vezzra** [comment]
Hm, ok, I can see where that would be not exactly optimal.

**Comment by Dilvish-fo** [comment]
Hmm, I was trying to look at the items that seem to render fine after RenderVisibilityRadii(), in comparison to RenderStarlanes() which doesn't.  It's been a while since I've worked on our rendering and my openGL knowledge is fading, and no conflict clearly jumps out, but @dbenage-cx to possibly help hone in on where the conflict is there, could you try running without your patch above, but with the option 
```--UI.resource-starlane-colouring 0```

**Comment by dbenage-cx** [comment]
> I assume the issue is for 0.4.6+ because that's the most recent FO release in the Fedora repos?

I did not catch the typo previously, should be 0.4.7+

The only option that appears to toggle render of starlanes is `UI.show-detection-range`.
(Edit: To be clear, I've verified `UI.resource-starlane-colouring` has no effect)

Taking another short look at this, the following diff also appears to work (though I do not notice a difference in render output on previous diff vs software render)
```diff
diff --git a/UI/MapWnd.cpp b/UI/MapWnd.cpp
index a5352c5f9..9dc9533d7 100644
--- a/UI/MapWnd.cpp
+++ b/UI/MapWnd.cpp
@@ -2127,7 +2127,6 @@ void MapWnd::RenderStarlanes(GG::GL2DVertexBuffer& vertices, GG::GLRGBAColorBuff
 
         glDisable(GL_TEXTURE_2D);
         glEnable(GL_LINE_SMOOTH);
-        glEnable(GL_LINE_STIPPLE);
 
         glLineWidth(static_cast<GLfloat>(thickness * GetOptionsDB().Get<double>("UI.starlane-thickness")));
         glLineStipple(1, 0xffff);   // solid line / no stipple
@@ -2155,7 +2154,6 @@ void MapWnd::RenderStarlanes(GG::GL2DVertexBuffer& vertices, GG::GLRGBAColorBuff
 
         glEnable(GL_TEXTURE_2D);
         glDisable(GL_LINE_SMOOTH);
-        glDisable(GL_LINE_STIPPLE);
     }
 
     glLineWidth(1.0);
```

I can only guess there is some issue(on my system) when enabling `GL_LINE_STIPPLE` after some stencil functionality was used/enabled.  Comment and [history](https://github.com/freeorion/freeorion/commit/24150f7c) leads me to believe removal would be fine, but I only partially understand glLineStipple [documentation](http://docs.gl/gl2/glLineStipple).

**Comment by Dilvish-fo** [comment]
> The only option that appears to toggle render of starlanes is UI.show-detection-range.
(Edit: To be clear, I've verified UI.resource-starlane-colouring has no effect)

I wasn't thinking it would totally toggle the rendering of starlanes, but it should certainly have an effect (at least if your starlanes were showing)-- it controls whether they get empire-colored for supply lines versus being all grey no matter what.  Given that RenderVisibilityRadii() enables GL_COLOR_ARRAY, and does its stenciling on a color-by-color basis, and the other rendering functions that do not seem to conflict with RenderVisibilityRadii() do not enable it, and RenderStarlanes() *does* also enable it by default unless you give the option setting I suggested, I thought it worthwhile checking if the conflict was related to the use of color arrays.

Anyways, your alternate solution of removing the line stippling does sound totally fine to me since it looks  like we still just do a solid line with no stipple no matter what, and we should probably also then remove the line
```
glLineStipple(1, 0xffff);   // solid line / no stipple
```

**Comment by geoffthemedio** [comment]
My quick search reveals no other uses of `glLineStipple` in FreeOrion code, so that line should be fine to remove.
