### ISSUE TITLE
Honor locale language env if no --stringtable-filename is given in parameters or set in the UI - linux

### ISSUE THREAD

**Issue by wrivas** [freeorion/freeorion#1811]
### Environment
linux FO 0.4.7.1

### Description
when my locale is fr 
(ex : LANG=fr_FR.UTF-8
LANGUAGE=fr_FR:fr
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
)

it would be nice for the UI to use the fr string table automatically.

keep the --strintable-filename options and the option in the UI, thoses are great
for override current locale.

thanks.

I understand this is a low-prio feature and it's ok. just consider it.

### Expected Result
if the locale is french, then start FO with the fr stringtable

### Steps to reproduce

export LC_ALL=fr_FR.UTF-8;export LANG=fr_FR.UTF-8;export LANGUAGE=fr_FR:fr
then : freeorion

**Comment by Dilvish-fo** [comment]
>  just consider it.

Sure, sounds like a good suggestion.

**Comment by dbenage-cx** [comment]
This feature is not yet supported when launching as an application on OS X.
Reopening so I don't lose track.

**Comment by ghost** [comment]
as of "FreeOrionCH v0.4.8 [build 2018-08-23.26f16b0] CMake" (that's why freeorion says on my debian system...) it's still not fixed.

It honors parts of the environment variables (text is in french by default, which is fine), but when spawning a 2nd interface of freeorion with specific envvar LANG=C, it does not work. Doing this is usually useful for coders to search informations or for contributors to give language agnostics reports.

Also, --stringtable-filename=en does not seems to work, guess the usual locales system is basically not used? If so, I guess it could be feature request (on the other hand, --help do not give any information about "--stringtable-filename" here).

**Comment by geoffthemedio** [comment]
`--stringtable-filename=en` is not a defined or correctly formatted command-line option for freeorion.

You probably want to use `--resource.stringtable.path` and specify the actual filename / path. Also, option values are not specified using `=`, but rather like `freeorion --ui.intro.menu.center.x 0`.

The system locale is checked to set the default stringtable, but not if the stringtable filename is already specified in the saved options. See https://github.com/freeorion/freeorion/blob/master/util/i18n.cpp#L39

**Comment by adrianbroher** [comment]
This should now be fixed with #2807 , I will give it a spin and report back.

**Comment by adrianbroher** [comment]
For my interpretation this works as expected, FreeOrion uses the value of LANG to configure the default value, unless an explicit persistent value is set in the configuration.

So this can be closed I guess.
