### ISSUE TITLE
When loading a game, the AI will replay its turn with different results

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1837]
Usually, the AI will begin turn X with a given AIstate ```pre_turn_X = post_turn_(X-1)```. After it has played the turn, the AIstate will be altered (```post_turn_X```).

When saving the game, AIstate ```post_turn_X``` will be saved. When loading the game, the AI will subsequently play the turn again - however with AIstate ```post_turn_X``` rather than ```pre_turn_X```. This may lead to different decision-making.

Furthermore, some orders may be issued a second time - for an example, see #1836.

The two straightforward approaches to fix this are both unsatisfactory.

A) In ```generateOrders```, check if the AI already played this turn (check an entry in the AIstate). If so, do not replay it. 
Problem: This makes debugging work more complicated as we can not simply modify some code and reload the game to check if it fixed the behavior. We would need a savegame one turn before the issue occurs which may very well not exist.

B) Always save the AI savegame state before ordering issues (e.g. keep a deepcopy of the pre-turn state or better: keep a savegame string from last turn even if no savegame was requested).
Problem: Issued orders still exist in the savegame. When code is modified and other issues will be ordered, there may be a mismatch between the AIstate and the actual orders issued. This is unacceptable.

A possible solution could be
C) Do not save the AI orders in the savegame (i.e. only save human orders). Always let the AI replay its turn on load. Save the pre-turn AIstate.

**Comment by Dilvish-fo** [comment]
A little while back, LGM-Doyle made it configurable in Options whether an autosave would be made at turn-begin or at turn-end.    Would you doublecheck if the use of the turn-begin autosave avoids this problem?

That wouldn't count as a perfect solution for a couple reasons (i.e. still a problem for impromptu debugging by someone who did not have the appropriate options set, and might make the human player renter moves required for the testing), but it would at least make the main problem avoidable with planning.

I agree with your concerns about approaches A and B.  I also agree that C sounds like a decent solution, subject to either (i)  confirming that in very large games and/or on marginal machines it does not generally notably add to the AIs game-load-turn processing time (I would expect that the AI would probably generally need about the same amount of time to process everything even with orders already in place, but it could be that having a large number of orderless fleets would add to the time), or (ii) making it controllable via Options so that non-testers could have the AI reuse the previously determined orders on game load.

**Comment by Morlic-fo** [comment]
> (i) confirming that in very large games and/or on marginal machines it does not generally notably add to the AIs game-load-turn processing time (I would expect that the AI would probably generally need about the same amount of time to process everything even with orders already in place, but it could be that having a large number of orderless fleets would add to the time),

Well, the turn-processing time would be the same as if the AI plays the turn for the first time, i.e. your normal turn-processing time... 

> (ii) making it controllable via Options so that non-testers could have the AI reuse the previously determined orders on game load.

This would require saving both pre- and post-turn AIstate (the pre-turn state will in general not be consistent with the issued orders). That does not necessarily disqualify that approach but it seems like a hassle if both ways to safe and load have to be maintained.

**Comment by Dilvish-fo** [comment]
> Well, the turn-processing time would be the same as if the AI plays the turn for the first time, i.e. your normal turn-processing time...

Yes, of course, but we've seen reports that for players playing big/long games that can get to be a very long time which they'd prefer to avoid on game load if they could.  But I suppose that doesn't matter so much now that we have quashed most memory leaks that could force people to need to restart the game frequently, and it would probably take a very large galaxy with a huge amount of AI fleets for the orderless fleet issue to make a noticeable difference.  So, OK, I withdraw the qualifications to my support for approach C.
