### ISSUE TITLE
Target industry/research meters consider last turn's population instead of current one

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1894]
The target research/industry meters are calculated with last turn's population, not the current one.

Steps to reproduce:
1) Have a planet with growing population on research/industry focus (so you get population dependent boni)
2) Check the meter effect accounting in the respective industry/research tooltip.

Result:
There will be an "unknown" penalty which is equivalent to the population difference since last turn times the resource output per population.
![effectaccountingbug](https://user-images.githubusercontent.com/11706951/33449915-72f06216-d60a-11e7-9cf2-61980789dedf.png)

Expected result:
The target meters are calculated with the current turn's population.

This also affects the AI: When manually calculating resource outputs (with the current population), you will get a different result than by querying the target meters (which are based on last turn's population).

**Comment by Dilvish-fo** [comment]
I think I know that cause of this, which is a bit broader of an issue and so I am describing in another issue that will reference this.

Also, though, based on my recollection from discussions long ago, some discrepancies along these lines could stem from a somewhat varying presentation of what is really a current meter value versus what is really an expected-next-turn value.  

It's my recollection that some of the values that the planet panel presents as apparently-current are actually "expected next turn" values, as this was deemed to be the more relevant data point for planning decisions.  Perhaps my recollection is stale or otherwise bad, but it's a strong enough recollection I thought I should note it for anyone who digs into such things.

**Comment by geoffthemedio** [comment]
The values shown in the GUI are, for resource meters, supposed to be what the planet will generate when "Turn" is pressed, not what it generated last turn. This means that if a planet's focus is changed, the result updates, rather than staying the same so that the player can't see the effect of the focus change.

Discrepancies in meter values should arise in cases where what the local client thinks the meter value should be based on its view of the universe, and what the server says it should be, are different. This discrepancy is calculated based on the situation at the start of the turn, and then considered to be the same even after things like focus changes during the turn, for purposes of predicting the meter values for the next turn cycle.

**Comment by geoffthemedio** [comment]
Is this still an issue?
