### ISSUE TITLE
SitRep Issue: Ancient Guardians self-destruct report for system not in my control

### ISSUE THREAD

**Issue by urshmost** [freeorion/freeorion#1933]
### Environment

* **FreeOrion Version**:  weekly test build 2018-01-02
* **Operating System**:  Win 7

### Description
On turn 154 I received a Sitrep message : 
  _On Alpaca: The Ancient Guardians self-destructed when the planet was captured! The planet is now an Outpost under your control._

Except I didn't capture a planet on the previous turn and Alpaca is not a system that I can even see on the galaxy map or in the Objects list.

### Expected Result
I would not have expected to see this message.

### Steps to reproduce
Load save game from turn 153 and replay.
[FreeOrion_Human_Player_Terran_0153_20180106_101847.zip](https://github.com/freeorion/freeorion/files/1609113/FreeOrion_Human_Player_Terran_0153_20180106_101847.zip)

**Comment by urshmost** [comment]
Also this sitrep is also displayed each subsequent turn.

**Comment by urshmost** [comment]
More info; On turn 153 I captured an Ancient Guardian planet that also contained Ancient Ruins which revealed a Dragon Tooth.  The Dragon Tooth ship, species Ancient Guradians, is named Alpaca, and I started receiving the message "On Alpaca: The Ancient Guardians self-destructed... etc". on the next turn.  There is no system named Alpaca, only the ship.

The messages that I received on turn 153 from capturing the planet were:
- A dragon tooth revealed in the ancient ruins
- Banforo found in ancient ruins
- Planet captured
- Ancient guardians self-destructed
- population died out.

Starting on the next turn, and continuing until the end of the game, was the message about "On Alpaca: The Ancient Guardians self-destructed... etc".

**Comment by dbenage-cx** [comment]
I find this situation kind of hilarious ;)  Can you resave the game in uncompressed xml please?

**Comment by MatGB** [comment]
Aha. This is *very* similar to one of the first bugs I helped fix when I started contributing, Acirema crewed ships would produce guard ships if they were stationary in systems that otherwise met the criteria. It's a fairly edge case problem so it rarely shows up.

Possible fixes: 

- set priorities for the guardians to implode before the ancient ruins can create a dragon tooth: as with all priority setting this has the potential to mess other things up so would need testing. 
- Stop guardians from spawning on planets protected by sentinels (we do at some point want a tougher version of them to replace some sentinels but that's a longer term objective for when the AI is better at dealing with them)
- have dragon tooth set to have no species at all, under any circumstance: I think this is my preferred approach given that it can end up with some very weird combinations and the new(ish) colonisation mechanics mean that they normally launch before a species has arrived; I have once had one crewed by Beige Goo, which stretched belief a bit more than normal.

(I have flu, so I'm not even going to look at the scripts, should be an easy job but the savegame would be very useful)

**Comment by Morlic-fo** [comment]
I opened #1940 with what is probably the simplest fix regarding the sitrep spam.

Whether or not the creation of the dragon tooth should be avoided at the first place is another question which I will leave to someone else.

**Comment by urshmost** [comment]
[Turn 153 - Ancient Guardians SitRep Issue.zip](https://github.com/freeorion/freeorion/files/1624559/Turn.153.-.Ancient.Guardians.SitRep.Issue.zip)
Here is the save file with both binary and compress xml disabled.

**Comment by dbenage-cx** [comment]
@urshmost Are you certain binary was unchecked? The upload is a binary archive

**Comment by urshmost** [comment]
[Turn 153 - Ancient Guardians SitRep Issue - No Bin.zip](https://github.com/freeorion/freeorion/files/1625050/Turn.153.-.Ancient.Guardians.SitRep.Issue.-.No.Bin.zip)
Lets try this again, file size is a lot bigger this time.  (I think there may be an issue about some option settings not taking effect until after a restart but that's for another day.)
