### ISSUE TITLE
[Organization] Add current stable branch to git for easy checkout

### ISSUE THREAD

**Issue by FalcoGer** [freeorion/freeorion#2004]
### Environment
**FreeOrion Version**: 0.4.7.1
* **Operating System**: Ubuntu 16.04 LTS
* **Fetched as**
  * Compiled from source: 7c6bb18d92f84ed049505d305b45c944db66da68

### Description
I use git for version control and wanted to play with a friend on windows. So I thought it's easy enough. checkout the stable version that is also available for download ion the release page.
But not a chance. The release page references commit 139ffd9b323ab7e9f9eeae3483a9c2f4eee87fcd
But trying to check it out results in:
```
~/freeorion>git checkout 139ffd9b323ab7e9f9eeae3483a9c2f4eee87fcd
fatal: reference is not a tree: 139ffd9b323ab7e9f9eeae3483a9c2f4eee87fcd
```
So I figured it would be in he v0.4.7 branch. but no, that doesn't include the v0.4.7.1 patch.

So I looked at the commit and used gitk --all to search for the specific commit message. I found the same changes in commit 7c6bb18d92f84ed049505d305b45c944db66da68
checking that out works as expected. Now trying to see if that actually playing nice with the windows version after another 2 hours of compiling.
Edit: It did not.

### Expected Result
1 git checkout stable
2 compile
3 done
4 profit

**Comment by dbenage-cx** [comment]
Release versions are managed by tags, try: `git checkout v0.4.7.1`

**Comment by FalcoGer** [comment]
I don't seem to be knowing how git works in such detail as to know what tags are. but perhaps such a thing should be included in the wiki for the compile instructions.
I've been messing with this stuff all evening and it's really frustrating.
Thanks for the quick answer.
Could you perhaps explain why I was unable to checkout 139ffd9 and why it has the exact same commit as 7c6bb18 ?
`git checkout v0.4.7.1` worked for me, it even checked out 139ffd9, which I couldn't do before manually for whatever freaking reason. v0.4.7.1 is not a branch either (but v0.4.7 is?). I'm confused.
Anyway, I'm gonna close this now.

**Comment by dbenage-cx** [comment]
> perhaps such a thing should be included in the wiki for the compile instructions

👍  Some generic list of quick setup steps would probably be useful.

Not sure why checkout failed for you, using the short form `git checkout 139ffd9` works for me. (this might be due to my local history already containing a previous reference).
I won't pretend to know all the details of git, but will note some details which might help clear up confusion.

Just looking at the changes in first commit may give impression they are the same.
However, if the hash reference is different, there is some difference between commits.
A notable difference is 139ffd9 is based on an altered history from 7c6bb18 (if viewing in browser, change `commit` to `commits` in url for history).

`v0.4.7.1` and `v0.4.7` are both tags, each referencing a specific commit. https://git-scm.com/docs/git-checkout#_detached_head might help clarify the difference between a tag and a branch.
