### ISSUE TITLE
Population dies out entirely on first turn.

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2046]
### Environment

* **FreeOrion Version**: 5f95edd153d97d454950ffaab29b1f6d46fcfd92
* **Operating System**: Gentoo Linux AMD64
* **Fetched as** 
  * Compiled from source

### Description
All populations entirely dies on first turn.

Turn 1: ![fo1](https://user-images.githubusercontent.com/397177/37256415-777b9886-256b-11e8-8444-a81a31cc1675.png)
Turn 2: ![fo2](https://user-images.githubusercontent.com/397177/37256416-7cab9f04-256b-11e8-97d8-88d27dc159b9.png)
Server log: [freeoriond.log](https://github.com/freeorion/freeorion/files/1800650/freeoriond.log)
Client log: [freeorion.log](https://github.com/freeorion/freeorion/files/1800652/freeorion.log)

### Expected Result
Population stays same.

### Steps to reproduce
* Start a game (same for multiplayer and singleplayer).
* Make a turn.

**Comment by Dilvish-fo** [comment]
My testing thus far indicates this bug is caused by a27b5102622f127de6ee669bc2f029de7cb2bf3e, which also (perhaps directly related, or perhaps as just another bug in the commit) causes the AIs to spam errors upon game start.  

The AI exceptions appear to come from the C++ side, reported as
```IndexError: Unable to find key in unordered_map```
which I have so far traced back through ```Pathfinder::ImmediateNeighbors()``` to 
```
std::multimap<double, int> ImmediateNeighborsImpl(const Graph& graph, int system_id,
                                                      const boost::unordered_map<int, size_t>& id_to_graph_index)
```

where it seems there are two potential triggers,
 [edge_weight_map[*it]](https://github.com/freeorion/freeorion/blob/5f95edd153d97d454950ffaab29b1f6d46fcfd92/universe/Pathfinder.cpp#L468), 
which itself does not appear necessarily erroneous to me, but is seemingly a bit fragile in that it assumes the key will actually be present (which of course it should be if all the related structures were coherent. but perhaps something is blocking them from being coherent)
or possibly stemming from 
[[sys_id_property_map[boost::target(*it, graph)]](https://github.com/freeorion/freeorion/blob/5f95edd153d97d454950ffaab29b1f6d46fcfd92/universe/Pathfinder.cpp#L469)

The only change the above commit made to this file certainly looks innocuous.  That's all I have so far, not sure how much longer I'll be able to look at this.

**Comment by adrianbroher** [comment]
I would guess this is caused by [universe/ObjectMap.cpp:147](https://github.com/freeorion/freeorion/commit/a27b5102622f127de6ee669bc2f029de7cb2bf3e#diff-121aa78a4fbff6e6f9a83a62dc0a93e7R174).

**Comment by Dilvish-fo** [comment]
> I would guess this is caused by [universe/ObjectMap.cpp:174]

Right, adding a ! at the beginning of that line fixes both this and 2044

**Comment by Dilvish-fo** [comment]
Since the wording of Marcel's comment above is suggestive of uncertainty, without an indication that he is able to continue following up on this right now, and I think this is mid-workday in Germany, I'll go ahead and push the fix.
