### ISSUE TITLE
Unable to Colonize a Suitable Planet at the Initial Turn

### ISSUE THREAD

**Issue by EnLightning** [freeorion/freeorion#2060]
### Environment

* **FreeOrion Version**:
v0.4.7+ [build 2018-03-19.104b3d4] MSVC 2015
* **Operating System**:
Windows 7 Pro
* **Fetched as**
  * Weekly development build

### Description
Our home system has 5 planets, one of them, Dairuin II is quite suitable. Try to colonize it at the first turn, failed. But if we advance to the 2nd turn, it can be colonized. 

### Steps to reproduce
* First step.
Load the save file [1.zip](https://github.com/freeorion/freeorion/files/1830927/1.zip)
* Second step.
In home system, try to colonize Dairuin II, but failed.
* Another step.
Advance to next turn, try to colonize Dairuin II, works.

**Comment by Dilvish-fo** [comment]
To add some to the problem description-- the 'colonize' button for the planet with the good environment is mostly unresponsive-- upon left mouse button depress it adjusts its appearance as appropriate, and upon left mouse button release it makes the appropriate clicking noise, but it does not otherwise respond.  The 'colonize' buttons for the poor environment planets in the same system, however, will respond just fine and allow you to try colonizing those planets.  Trace logging for the client seems to add nothing helpful.

**Comment by Dilvish-fo** [comment]
OK, well I have this _pretty much_ figured out, the complication in this case is that tidal lock special which applies a -3 target pop effect even if there is no species on the planet.  After the first bit of universe creation the planet winds up with a population meter at something like -1.2, and upon loading of this savegame that planet pop meter is at Init -0.3  Current 0.0.   Having an init pop of anything other than zero blocks the colonization attempt.  At turn 2 that meter has settled down to Init 0.0 Current 0.0

Having an (additional) extra round of meter application/backpropagation prior to turn 1 might prevent the problem in this particular case, but that might be a bit dependent on the particular values of this special (so not as general a solution as I think we should ideally come up with, and there are other specials with similar effects that we'll want to similarly address).

Perhaps the planet pop growth code should double check if the species is blank and set the meters to zero in that case.

A solution that I tested was to add an activation condition to the special so that this pop effect would only try to apply itself if there actually was a species:
```
activation = Species
```
This appeared to solve the problem fine without any negative side effects that I could see.  So unless someone has other thoughts, this is the solution I'll go with (and I'll check other specials like temporal anomaly and worldtree also)

**Comment by Vezzra** [comment]
> After the first bit of universe creation the planet winds up with a population meter at something like -1.2

I wonder why... I mean, there are three calls to `SetActiveMetersToTargetMaxCurrentValues` in [`ServerApp::GenerateUniverse`](https://github.com/freeorion/freeorion/blob/a6ab2f157c20e8431a520e428582addf05a180a2/server/ServerApp.cpp#L1363), I always thought these should ensure that on turn 1 all current meters are at the target/max value?

> This appeared to solve the problem fine without any negative side effects that I could see

So the habitability report still works fine for planets with the Tidal Lock special and that fix applied? Showing the correct target pop (including the effect of the Tidal Lock special)?

**Comment by Dilvish-fo** [comment]
> So the habitability report still works fine for planets with the Tidal Lock special and that fix applied? Showing the correct target pop (including the effect of the Tidal Lock special)?

Yes.

**Comment by Vezzra** [comment]
Excellent 👍
