### ISSUE TITLE
Can't Load Compressed XML Saves with SDK9

### ISSUE THREAD

**Issue by Houkime** [freeorion/freeorion#2132]
### Environment
Arch Linux as of 28.05.18
8GB DDR4 (no, it was not overflowing).
Boost 1.66
compiling from master at 2095b8991321c39f803cc1c4b0ed7fb9a96a5c89 (28.05.18)

### Description

On load of any save gets disconnected from server.

console output:

```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error-Cannot allocate memory
[remainder removed by Geoff due to extreme length]
```
[output ends here - we're back in the menu]
Other logs:

[AI_1.log](https://github.com/freeorion/freeorion/files/2045927/AI_1.log)
[AI_2.log](https://github.com/freeorion/freeorion/files/2045928/AI_2.log)
[AI_3.log](https://github.com/freeorion/freeorion/files/2045929/AI_3.log)
[AI_4.log](https://github.com/freeorion/freeorion/files/2045930/AI_4.log)
[AI_5.log](https://github.com/freeorion/freeorion/files/2045931/AI_5.log)
[AI_6.log](https://github.com/freeorion/freeorion/files/2045932/AI_6.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/2045933/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/2045934/freeoriond.log)

### Expected Result
Game loading.

### Steps to reproduce

* Install latest Arch (IDK about other distros)
* Download, compile, install and launch the game (yes, only 4 rows needed for this ^_^ ):

```
git clone https://aur.archlinux.org/freeorion-git.git
cd freeorion-git
makepkg -si 
freeorion
```
* make a clean start.
* save game
* resign
* load your save

**Comment by geoffthemedio** [comment]
Edited your comment due to the length of the mostly irrelevant console output.

Seeing same error on Windows. Trying some earlier versions to see if a recent commit or pull request merge is the cause...

a6b360d works with MSVC2015
3cc7176 works with MSVC2015 and SDK5 but does not work with 2017 and SDK9, nor with 2015 and SDK9.
3a23122 (effectively latest master) works with MSVC2017 and SDK5.

@adrianbroher could this be an issue with the newer boost version?

**Comment by Houkime** [comment]
Yep, this works.
Save size is around 350 kb per save if using binary (x2 compared to compressed xml).

**Comment by geoffthemedio** [comment]
Are you able to build against any earlier boost versions?

**Comment by adrianbroher** [comment]
@geoffthemedio that's the most likely cause.

**Comment by adrianbroher** [comment]
zlib could also be the cause.

**Comment by Houkime** [comment]
I almost certainly can (though there was no need for such operations yet).
And against 1.67 also.
Will look into it shortly.

**Comment by adrianbroher** [comment]
Not reproducible with:
```
22:28:55.192002 [info] client : DependencyVersions.cpp:84 : Boost: 1_64
22:28:55.192163 [info] client : DependencyVersions.cpp:84 : zlib: 1.2.11
```

**Comment by Vezzra** [comment]
~~@geoffthemedio, @adrianbroher, can I safely assume this issue does not affect the release branch, only master?~~ Nevermind, just made sure by running a quick test, the release branch doesn't have the issue.

**Comment by geoffthemedio** [comment]
As long as you build against the older SDK, I think it should work fine.

**Comment by Houkime** [comment]
For win IDK, for Linux (and maybe Apple thingies) this is not an option.
Boost runtime libs are installed system-wide. When FO runs on newer Boost libs the error with saves will occur.
You can't really ask people to downgrade their Boost just for FO - this will cause all kinds of trouble.

BTW you probably don't know but in Boost 1.67 python and python3 libs were renamed to python27 and python36 (for some unknown reason) which might add extra obstacle when ensuring coexistence of old-boost FO with other boost apps on one machine.

I recommend you to consult with the maintainer here https://github.com/boostorg/serialization on your issue or make xml compression of saves _not_ default.

**Comment by geoffthemedio** [comment]
Compressed XML is used for a reason, which is that uncompressed XML saves can be huge.

Regardless, it's not clear what actually is the problem yet. Possibly it's a zlib issue as @adrianbroher noted. It's not clear if the save is broken, or loading of good saves is broken. If a particular good / bad version of whatever library is the issue can be identified, then default use of compression can be set accordingly, since the dependency versions are available at runtime. If it's a loading issue, then that won't help someone using a bad dependency to load others' saves, but it will at least have them make saves they can load for themselves.

**Comment by geoffthemedio** [comment]
@Houkime @adrianbroher Could one or both of you check if the issue happens when trying to load a save from an older version of boost / zlib (that can load its own saves) with a newer version, and the other way around? Would be good to know if it's the saves that are broken, or just the loading of the saves.

For me using MSVC 2017, an uncompressed save made with SDK5 can be loaded with SDK9, but a compressed save made with SDK5 can't be loaded with SDK9.

**Comment by adrianbroher** [comment]
I really don't want to bisect this unless it can't be avoided.  @Houkime can you upload a sample save game file, which cannot be loaded?

**Comment by geoffthemedio** [comment]
@adrianbroher  For me using MSVC 2017, a compressed save made with SDK9 or SDK5 can't be loaded with SDK9. A compressed save made with SDK9 or SDK5 can be loaded with SDK5. Uncompressed saves seem to work in any case.

So, I don't think it's a problem with the save files themselves, but rather with the SDK9 (and presumably 10) decompression.

[comp_and_uncomp_saves.zip](https://github.com/freeorion/freeorion/files/2059630/comp_and_uncomp_saves.zip)

**Comment by adrianbroher** [comment]
Geoff, I still need some reference file to work with.

**Comment by geoffthemedio** [comment]
There is a zip with save files attached in my previous comment. If you can replicate the issue with boost 1.66 then you can make one easily for yourself though, by just quickstarting a game and ending turn once to get an autosave.

**Comment by Vezzra** [comment]
> For win IDK, for Linux (and maybe Apple thingies) this is not an option.

The OSX app bundle includes it's own version of the boost libraries, so it's not dependent on an external boost version. Which means, at least as far as the release branch is concerned, there won't be issues on OSX as the release branch is still built against version 8 of the SDK (which, using older boost versions, isn't affected by the issue).

The same applies to Windows.

However, following this discussion leaves me with the impression that this issue will affect the 0.4.8 release on Linux, because there we don't provide prebuilt binaries, but source tarballs, that are built against the boost versions the various distros provide. If those boost versions happen to be among those that are affected by this bug, the 0.4.8 release will essentially be broken on those platforms.

Is that assessment correct? If yes, I'm inclined to consider this as an release blocking issue (provided there is anything we can do to work around this boost bug - if not, no point in delaying the release for something we can't do anything about). @geoffthemedio? @adrianbroher?

**Comment by geoffthemedio** [comment]
If the issue is zlib-version dependent, then there are limit to what can be done as a workaround. The saves themselves don't seem to be broken; rather the library that decompresses them is. We can make the default to not create compressed xml saves if the zlib library on a system is known to be broken, but that won't let that client load compressed saves from someone else.

Hopefully @adrianbroher can clarify what the zlib version dependence is. I can't easily build against various different zlib versions.

**Comment by Vezzra** [comment]
> We can make the default to not create compressed xml saves if the zlib library on a system is known to be broken, but that won't let that client load compressed saves from someone else.

Well, in that case at least that workaround should go into 0.4.8, and a respective note into the changelog as a known issue on Linux ("due to a bug in certain boost/zlib versions loading of compressed XML saves does not to work on all Linux distros" or something along these lines).

**Comment by Houkime** [comment]
If the case is in the underlying library being wrong one should at least create an issue on this library SVC/bugtracker page to get it fixed in future releases/ receive an insight on possible workarounds.

**Comment by Houkime** [comment]
Issue is not reproducable with zlib 1.2.9 and Boost 1.67
Except for some rare saves all saves that were made even in broken variants can be loaded.

**Comment by Houkime** [comment]
So it is not the Boost or zlib on its own, but the combination of two. because 1.64+1.2.11 works and 1.67+1.2.9 also works.
It is a compatibility problem here.
Hierarchy-wise fixing this rather lies on boost-libs because it's _them_ who use zlib and not vice-versa.

**Comment by geoffthemedio** [comment]
If you can determine as many combinations that do / don't work, or the limits on version numbers that do or don't work, then we can use those to determine the default for whether to enable XML save compression. Like,
````
bool default_use_xml_compression = true;
if (boost_version > 1.64 && zlib_version < 1.2.11)
    default_use_xml_compression = false;
````

**Comment by adrianbroher** [comment]
@Vezzra 
> Is that assessment correct?

Yes it is.

> If yes, I'm inclined to consider this as an release blocking issue (provided there is anything we can do to work around this boost bug - if not, no point in delaying the release for something we can't do anything about).

This should depend whether this is a boost bug or wrong usage of boost serialization by us that was just uncovered by a more recent version of boost.

@Houkime 

> If the case is in the underlying library being wrong one should at least create an issue on this library SVC/bugtracker page to get it fixed in future releases/ receive an insight on possible workarounds.

True, but currently it's not clear what the actual cause for this bug.  Also before stirring up anything upstream I would prefer to come up with a repeatable example and a commit causing this.  Going there with something like "our code broke somewhere between those n-hundred commits of your lib but we don't know why" never leads to any useful outcome.

**Comment by adrianbroher** [comment]
FYI:

Working: boost_1.65.1
Broken: boost_1.66.0

Now trying to bisect the broken commit of boost::serialization.

**Comment by adrianbroher** [comment]
First commit introducing the bug: boostorg/serialization@64dc62099238a44341132d7cd4e237d1c1004020

**Comment by adrianbroher** [comment]
I would say we are relying on incorrect behavior.  The written save files declare in their header that they are UTF-8 encoded. By adding the `compress`ed bytestream, which contains invalid UTF-8 sequences, the boost serialization xml loader (>=1.66.0) starts to correct those invalid byte sequences by replacing them with `U+FFFD`, which causes the zlib decompression to allocate a huge buffer.  This fails with the exception mentioned in OP.

A proper fix would be to store the `compressed` stream as valid UTF-8 string, BASE64 encoding for example.

**Comment by geoffthemedio** [comment]
If https://github.com/tkislan/base64 just works, then it shouldn't be too complicated to add a BASE64 layer...

**Comment by adrianbroher** [comment]
Looks ugly, also doesn't integrate with boost::serialization or boost::iostreams. This looks better: https://github.com/sneumann/mzR/blob/master/src/boost_aux/boost/iostreams/filter/base64.hpp

**Comment by Dilvish-fo** [comment]
I can't claim to be well versed in this area, but it looks to me like very little is needed to simply use the regular boost base64 dataflow iterator encoders/decoders https://www.boost.org/doc/libs/1_67_0/libs/serialization/doc/dataflow.html

which at first glance appear to be available at least as early as our min req boost 1.58 https://www.boost.org/doc/libs/1_58_0/boost/archive/iterators/base64_from_binary.hpp

Am I overlooking something?

**Comment by adrianbroher** [comment]
> Am I overlooking something?

Yes, there is no easy way to integrate it into a boost::iostreams sink or source.

**Comment by adrianbroher** [comment]
@geoffthemedio why is the AI state zlib compressed in the first place?

**Comment by geoffthemedio** [comment]
probably to make it smaller / faster to save and transfer...

**Comment by Dilvish-fo** [comment]
> Would it make sense to also run the base64 conversion on the AI save state string? The description of build_savegame_string says it uses zlib compression.

Yes, I think it would be helpful, to deal with [the issue I noted in a recent discussion](https://github.com/freeorion/freeorion/pull/2122#issuecomment-392583446), so I've opened #2142
