### ISSUE TITLE
Target meters not showing actual target when current meters are hold to zero

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2184]
### Description
Effects that hold to zero a current Meter do not show it properly in the visible effects when there are other (previous) bonuses applying to TargetMeter.

Dilvish wrote [in the forum](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10999#p93086):
> [...] the current implementation of that seems a bit buggy to me since if it is going to hold the primary meter to zero it should also hold the target meter to zero.

### Expected Result
Effects that hold current Meter to zero should also hold TargetMeter to zero.

**Comment by geoffthemedio** [comment]
I think this is working as intended, or at least misnamed. If there is some effect setting a current meter to 0, that has no impact on what the target meter is. The normal meter growth is just being overridden. The target still has whatever value it has.

**Comment by Oberlus** [comment]
The suggestion then would be to show an extra visible effect in the tooltip (something like "XXX effect: -TargetMetr") to let the player know what/why is holding the value to zero if the visible effects show a positive target meter.

**Comment by Dilvish-fo** [comment]
> If there is some effect setting a current meter to 0, that has no impact on what the target meter is. The normal meter growth is just being overridden. The target still has whatever value it has.

I agree that in general, it could possibly make sense that there was some effect temporarily holding a primary meter at zero, while the target meter still stayed positive.  But that really only makes sense to me if the effect is caused by something that is explicitly transient.

The particular instance where this currently arises is with respect to the effect that "// removes residual production from a dead planet" and it really doesn't make sense to me for such an effect to apply to the primary meter but not the target meter.

I'm fine with calling this a 'tweak' type improvement issue rather than a 'bug', but it is something that has always seemed a bit awkward/wrong to me, and I certainly think it could be improved.

**Comment by Dilvish-fo** [comment]
Perhaps that particular one won't matter so much if we actually restrict it to truly "dead" planets and not apply it to all apparently-dying ones.   But it still seems to me that the general rule ought to be that if you hold the primary meter to zero you should do the same for the target unless there is something specifically intended to be communicated by not holding the target to zero.

**Comment by Vezzra** [comment]
> The particular instance where this currently arises is with respect to the effect that "// removes residual production from a dead planet" and it really doesn't make sense to me for such an effect to apply to the primary meter but not the target meter.

I have to say I share this sentiment.

**Comment by Vezzra** [comment]
Lets agree to tag this as both bug/tweak :wink:
