### ISSUE TITLE
Handling of Dead versus Dying colonies

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2185]
### Description
The handling of dying colonies my be buggy. If I understood it correctly, the effect that handles it does treat the same dying (diminishing populations) and dead (already zeroed) colonies, why it probably should only apply to dead colonies.

Dilvish wrote:
> the comment description is "// removes residual production from a dead planet" whereas the implementation applies to any dying planet

**Comment by Oberlus** [comment]
I don't really know, it was Dilvish who spotted this. We shall wait for @Dilvish-fo and his clarity of thought and speech.

**Comment by Dilvish-fo** [comment]
>What actual in-game consequence does this have? It's not clear what the problem is or how (you think) it should work differently.

The simple summary of my recollection of ingame consequences is that it can often wind up zero-ing out meters on planets that are not actually dead, nor even really on the actual cusp of dying-- it has just seemed to me to be an over-active effect.  

Consider, for example, a large planet whose owner has a bit of tech, making the default target pop on the planet zero, but it is supply connected to an active growth special so the target pop is 4.  (And perhaps these particular numbers only work out with our current techs if there is also a growth special on the planet itself, I don't quite remember).  Suppose the planet is currently at population 3 when it loses supply connection to the active growth special, due to a blockade, dropping its target population down to zero.  Although it would take a tremendous number of turns for the planet to actually hit zero current pop and die out to an outpost, and would still take a fair number of turns for the actual current pop to even drop below one, it is my recollection that this effect would zero out the industry and research current meters during that time until the supply connection to the growth special were resumed.  

That has always seemed a bit overdone to me, and it is overactive relative to the stated comment as well.  By the stated intent of the comment it seems to me that it could just as well wait until the actual population is zero rather than just going off the target population.

And even if there was some reason for it to kick in before the actual pop quite hit zero, it seems there should at least be a ceiling of actual pop (say, perhaps 0.3) above which it did not kick in.  (And then the comment should be adjusted to note it applies to planets that are dead or on the cusp of dying.)

**Comment by Dilvish-fo** [comment]
For reference:
[industry.macros#L38-L45](https://github.com/freeorion/freeorion/blob/863b7a016afae852c8566873de9090c7529f4323/default/scripting/species/common/industry.macros#L38-L45)

**Comment by Dilvish-fo** [comment]
> So, would this work?

That structure should work fine.  

If you're planning on submitting a PR for this, I'd recommend pulling all the various parallel pieces out into a single DYING_PLANET_CHECK macro to get referenced in BASIC_POPULATION just like I talked about in #2183.  Or at least make a macro 
```
MIN_ACTIVE_POPULATION
0.1
```
that could be referenced by all the respective parts so that if we change the number we only need to change it one place.  (That number definition should probably go into species/common/general.macros) Also, since it looks to me like this bit of script is directly adjacent to the lines involved in #2183, to avoid a ton of merge conflicts I think I'd recommend both be dealt with in the same PR (but a different commit corresponding to each issue)
