### ISSUE TITLE
Fleet window size/position resets always

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#225]
The changes introduced by @mel-odious [Remember window positions](https://github.com/freeorion/freeorion/pull/214) PR work really well, with one notable exception however: the fleet window not only doesn't remember it's size and position like the other windows do now, but resets size and position _each time you cklick on a fleet_.

So, for this particular window the behaviour is worse than before. Each time I click on a fleet, the fleet window gets resized and moved to its default position in the lower left corner of the map window.

Issue observed with build 2015-07-17.927e515 on OSX.

**Comment by mel-odious** [comment]
Compiling now to attempt to reproduce, but one possible cause comes to mind: if the 'reset window positions' toggle is enabled, the fleet window will always reload its default positions because those windows are created/destroyed constantly unlike most other windows that are merely hidden form view.  The toggle is only supposed to be enabled until you've opened the windows you want to be reset, and can be disabled afterwards...  Already solved on my local branch by replacing that toggle with a more intuitive and useful solution, but for now you could double-check if it happens with that toggle disabled.

**Comment by Vezzra** [comment]
I've already checked that toggle, it gets automatically cleared anyway after the windows positions have been reset, no? Or at least after an app restart? I had repeatedly restarted FO with the toggle disabled, and the issue persisted.

However, now a very strange thing happened.... I just resumed my test game (with exact the same build), and now the fleet window remembers its size and position perfectly, just as all the other windows. Can't reproduce the issue anymore.

So I'm closing this issue, and hopefully your fix solved what erratic thing has been going on in the background.

Thanks for looking into the matter so quickly :smiley:

**Comment by mel-odious** [comment]
It doesn't get reset after it repositions things, which is partly why it's so awkward and strange ;p
I was able to reproduce the issue, so for the benefit of everyone else who runs into this:
Single fleet window mode, 'reset window positions' toggle enabled:
- click on a fleet to open a fleet window
- move the fleet window
- click on another fleet (not in the same system), the fleet window moves back to its default position

Workaround: don't keep the 'reset window positions' toggle enabled all the time, it's only a toggle instead of a button because some windows need to be opened to have their positions reset and it can be disabled after you've opened all the windows that you want to reset.

I've 'fixed' this, i.e. replaced the awkward toggle option with a more thorough solution and it will be up before the release deadline.
