### ISSUE TITLE
Fields start too far outside map edges on large maps

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#229]
Something I've observed for a very long time now: On large maps fields are created so far outside, that by the time they reach the outer systems they've already shrunk so much that they dissipate before they really get into the map.

Apparently their starting distance to the map edges is calculated proportional to the map size/universe width (which made the problem even worse on those galaxy shapes that set a bigger universe width upon map creation, which I tried to alleviate a bit with commit [97cc19f](https://github.com/freeorion/freeorion/commit/97cc19f9291239224e48b55fea26627feff58e80)). However, it seems that the rate which they are shrinking at isn't proportional to the distince to the map center, resulting in them dissipating too quickly.

**Comment by geoffthemedio** [comment]
Dissipation is based on proximity to systems, no distance from map centre. If they start out extra far, they won't dissipate at all until they've moved into close range of some systems.

See: https://github.com/freeorion/freeorion/blob/master/default/fields.txt#L15

(The comment above that about growing when near stars seems to be inaccurate...)

**Comment by Vezzra** [comment]
Hm, well, then something else isn't working as intended. I ran several tests, and on small maps those fields got far into the map, but on large maps they just get to skirting around the systems on the edge of the map before they dissipate. They're basically just eye candy on those maps (if you get to see them at all, that is).

Maybe the problem is that on large maps the fields have to travel far longer on the map edges before they spiral inward, and as the rate of dissipation isn't correlated to the map size, they just don't make it very far?

**Comment by geoffthemedio** [comment]
They probably travel about the same distance "near" systems, but on a large map that only covers the peripheral bits, while on a smaller map the same distance is a larger fraction of the way into the bulk of the galaxy. Possibly also they are moving more circumferentially than radially on larger maps, which would let them move less distance in before dissipating. Note that the range of dissipation effects is 80 uu from the edge of the field, not the centre.

If you want to tweak the dissipation formulas, feel free to try...

**Comment by Vezzra** [comment]
Ok, did some experimenting. Tried to change the numbers a bit (reduced the range of the dissipation effects), but that's almost impossible to get right - either the fields dissipate too slowly on smaller maps (leading to an accumulation of fields in the center) or too quickly on larger maps.

Will continue experimenting, but close this issue for now.

**Comment by Dilvish-fo** [comment]
Did you try making your dissipation settings dependent on the galaxy size?

**Comment by Vezzra** [comment]
My next tries will be something like factoring in the distance to the map center. Your suggestion might be another way to fix that. Will continue experimenting tomorrow.

**Comment by geoffthemedio** [comment]
I wanted to avoid anything non-local affecting fields behavior, such as distance to an arbitrary galaxy centre. If there's nothing in that region, then the fields should pass through unaffected.

**Comment by Vezzra** [comment]
Hm, but in this case your implementation of field behaviour is a bit inconsistent? Because as far as the movement of fields is concerned, you actually used the non-local arbitrary galaxy center as the ultimate destination all fields spiral into. But you don't want to factor in the distance to that destination into the dissipation effects, which results in the problematic behaviour we have now.

> If there's nothing in that region, then the fields should pass through unaffected.

Well, that's the problem - they don't pass through that region, they hover there once they get there. And if that region happens to be empty, they would do so indefinitely. The hovering happens on sufficiently small maps already with your original settings. With a ring shaped galaxy, the indefinitely hovering part might happen too, have to test that actually...

Anyway, if we want the fields to actually get deeper into the map instead of just skirting around the edges, we have to factor in the map size one way or the other. Wether we use the universe width value or the distance to the center doesn't make much difference I guess?

I can't think of any other solution that could be implemented in FOCS...

**Comment by geoffthemedio** [comment]
Field movement and field dissipation are separate calculations.

The movement spiraling around the nominal galaxy centre is just what I wrote as a first pass, because it was simple and easy to get working. There could be better implementations, perhaps one that gives a proper elliptical orbit, although this would require some additional state information in the field to track the velocity independent of the position, and perhaps require some additional calculations of the gravitational effects of all systems in order to avoid using the nominal centre point in the calculation.

I don't think it's necessarily a problem if fields don't ever make it to the centre of the galaxy if they start on the periphery... this makes the outer edges of the galaxy a bit distinct. And there can be additional field types added that exist primarily in the centre, such as a high radiation region or similar. I'm somewhat interested in doing this to give the map more strategically interesting structure, similar to oceans on a planet map in a Civ game, and to better mark regions where it's less likely to find habitable planets, or similar.

Fields pooling up in the empty centre is an issue. Does that happen with existing settings for field movement and dissipation?

**Comment by geoffthemedio** [comment]
I don't think differing penetration depths is a problem... just a distinction between the types of field.

Rather than a radial-distance dependent decay factor, I'd try adding a time-dependent size adjustment, so the storms start small, grow bigger, then shrink and disappear with time, in addition to any system-proximity effects.

Making the distance a constant addition to the galaxy size for the spawn locations sounds good.

**Comment by Dilvish-fo** [comment]
> Rather than a radial-distance dependent decay factor,

I'm not really understanding the opposition to this. It's a fairly inexpensive calculation-- we don't have to do a weighted center, we can just use the Cartesian center.  If you want to void having all fields at distance X from the center having the same size, then just add a little random component to it as well, that gets dominated more and more by the fixed component as they get closer to the center, so that you can be sure they won't last forever in the center.

**Comment by Vezzra** [comment]
Ok, I've been experimenting a lot today with all kinds of numbers. Getting those numbers right for several interacting grow/decay functions so that they work at least reasonably well for map sizes from 30 to 500 turned out to be very difficult. The end result either doesn't work for small maps, or large maps, or one function dominates so much that the other function becomes pointless.

I'd have to invest far more time to get satisfying results, not really feasible so close to the release.

So I settled for something simple that IMO still works a bit better than the original implementation. I used Geoffs idea of a time-dependent grow/decay function. Fields spawn small, grow until they reach a certain age, then shrink and dissipate. The typical "life span" of a field is determined based on universe width. The other decay function (shrink near systems) I commented out.

See commit 46c1d1b73113c38c8a210077de4f100ae9d959f6.
