### ISSUE TITLE
An unarmed ship entering a system with an armed ship set to blockade/attack is not attacked.

### ISSUE THREAD

**Issue by krivit** [freeorion/freeorion#2312]
### Environment

* **FreeOrion Version**: db69f1b9c25
* **Operating System**: Debian GNU/Linux mix of stable and testing
* **Fetched as**
  * Compiled from source

### Steps to reproduce

1. Download [the attached saved game](https://github.com/freeorion/freeorion/files/2522502/No_combat.sav.gz) and uncompress it using `gunzip`.
1. Start FreeOrion and load the saved game. Observe that an unarmed tame Small Snowflake belonging to the Dark Blue AI player is about to enter the Xenon δ system, which contains an armed ship Antares of the Light Blue human player.
1. Press CTRL-ENTER or otherwise advance the turn.
* **Expected result**: The Snowflake enters Xenon δ, and Antares attacks the Snowflake.
* **Actual result**: The Snowflake enters Xenon δ, and Antares and the Snowflake do not engage in combat. The Snowflake is able to leave the system on the next turn via a different starlane.

### Description

The unambiguous symptom is, as in the Subject, an unarmed ship entering a system with an armed ship set to blockade/attack not being attacked. The bug itself may have to do with lookup mechanism for whether two empires are at war.

[Attached `freeoriond.log`](https://github.com/freeorion/freeorion/files/2522505/freeoriond.log) contains the following messages that look relevant:
```
13:10:34.698120 [debug] combat : ServerApp.cpp:2034 : CombatConditionsInSystem() for system (1035) Xenon δ
13:10:34.698131 [debug] combat : ServerApp.cpp:2048 :    Empire 1 has at least one aggressive fleet present
13:10:34.698150 [error] server : EmpireManager.cpp:147 : Couldn't find diplomatic status between empires 1 and 3
13:10:34.698165 [debug] combat : ServerApp.cpp:2092 :    No warring combatants present: no combat.
```
[`freeorion.log`](https://github.com/freeorion/freeorion/files/2522504/freeorion.log) is also attached.

**Comment by Oberlus** [comment]
I've encountered this too. One of the starting scouts of my enemy went over my standing still, aggressive frigate past my homeworld, so it's not ligated to the offending unarmed ship being a monster as in the OP save game, and stealth is not the problem (in my case, the scout is 5 and there is no ion storm or other effects, it's turn 10). However, this does not happen consistently, most of the time the incoming enemy unarmed ship is attacked when it gets to a defended system.
Also, in the OP save, I tried to pursue and kill the small snowflake but again no combat ensued when my aggressive armed ship and the unarmed small snowflake were together on other systems.
PS: no need to say that this seems a rather serious bug for multiplayer.

**Comment by geoffthemedio** [comment]
The issue in this save appears to be that diplomacy is broken. This can be seen in game by all the diplomatic statuses between the player and other empires shown as "?" and not being able to right-click any of the other empires in the players list to declare war or peace. The battle doesn't happen because the player isn't at war with the blue empire.

In the save, there are diplomatic statuses recorded, but they all have at least one non-existant empire IP.

I have no idea how this happened, but I can add stuff to the loading code to sanitize diplomatic statuses.

**Comment by Vezzra** [comment]
> I have no idea how this happened, but I can add stuff to the loading code to sanitize diplomatic statuses.

While that will clean up the save, we still need to find out what caused the issue and address it. The question is, is there a way to reliably reproduce the issue? @krivit, @Oberlus?

If not, adding some sanitizing stuff to the loading code is all that can be done for 0.4.9. I'd remove the 0.4.9 milestone from this issue here as soon as that has been done. Doesn't make sense to block the release for a bug that can't be reproduced.

**Comment by geoffthemedio** [comment]
The issue was reported a year ago and not really recognized at the time for what it was (diplomacy vs. battle mechanics), so I doubt it will easily be reproduced. May have been incidentally fixed anyway if related to mixing up player and empire IDs, or it could perhaps have been due to version conflicts in saves created in an earlier version and loaded in a later version. If it was a version transition issue, it would be not be an issue with the current version in particular, or even necessarily possible to fix in master now... But if reproducible, within a single version, even if not the current, that would be good to know.

**Comment by Oberlus** [comment]
I haven't seen this happening again, although I'm not playing much these days (only slow-game multiplayer). I'll keep an eye on this and upload a save if it happens again.

**Comment by krivit** [comment]
I recall running into this issue often enough that I stopped playing FreeOrion after reporting the bug, so I don't know if it's still present. I can try installing the latest `master` and seeing if it shows up in the little time I have to play at this point.

**Comment by Vezzra** [comment]
@krivit,

> I can try installing the latest master and seeing if it shows up in the little time I have to play at this point.

Thanks, that would be much appreciated!

**Comment by geoffthemedio** [comment]
@krivit your testing reports would be appreciated

**Comment by krivit** [comment]
I haven't encountered the issue in the build from 38fdd70417276be55e970ae07eec575d2e6aa76b, for what it's worth.
