### ISSUE TITLE
[Bugfix patch] unsigned integer underflow in GG::Edit::AdjustView

### ISSUE THREAD

**Issue by ischwarze** [freeorion/freeorion#2314]
### Environment

* **FreeOrion Version**: git commit d62cfa57 (Oct 21 19:32:03 2018) + private patches (which i'm going to submit separately, later on)
* **Operating System**: OpenBSD-current

### Description

In GG::Edit::AdjustView(), underflow checking is done the wrong way.  To see whether a `size_t` value is greater than 5, the test "X - 5 > 0" is ineffective because if X is less than 5, then X - 5 is a huge positive number.

This caused a segfault in the client for me when editing a long string in a narrow window.  Since i'm always playing with debugging symbols compiled in, i was able to track down the root cause by looking at the backtrace from the core dump in GDB, identifying the following corrupt data,

    #0  0x0000017f3f717094 in GG::Edit::FirstCharOffset (this=<optimized out>)
    at /usr/ports/pobj/freeorion-0.4.8.1/src-tarball/GG/src/Edit.cpp:295
    #1  GG::Edit::Render (this=0x17f67be9000)
    at /usr/ports/pobj/freeorion-0.4.8.1/src-tarball/GG/src/Edit.cpp:126
    (gdb) p this->m_first_char_shown
    $9 = {m_value = 18446744073709551615}

then grepping the code for places where `m_first_char_shown` is modified, looking specifically for subtractions.

With the attached patch, the crash did not occur again.
[0001-fix-unsigned-integer-underflow-bug-in-GG-Edit-Adjust.patch.txt](https://github.com/freeorion/freeorion/files/2545639/0001-fix-unsigned-integer-underflow-bug-in-GG-Edit-Adjust.patch.txt)

**Comment by geoffthemedio** [comment]
Thanks, committed: https://github.com/freeorion/freeorion/commit/25ae12b6014258ee02f24efb6993c8a8f11194fc

**Comment by Vezzra** [comment]
> Hmm, although if we went ahead and made a Project for the bugfix release, then I suppose we could make project cards for individual commits then, I think.

Yes, but until a definite decision about that bugfix release has been made and such a project gets opened, tagging issues like this as "cherry-pick for release" is a good idea anyway.

**Comment by Vezzra** [comment]
Thanks for the input, I've been considering that approach already. Our experience with bugfix releases is, well, very limited, we never did that until 0.4.7, which was the first version to receive a bugfix release.

The thing is, if you decide to take that approach, you need to be disciplined about it. Whenever a bugfix goes in that fixes an issue that has already been present in the latest stable release (and not introduced into master only later), it needs to be cherry picked to the (bugfix) release branch right away. Otherwise it very likely is going to be forgotten.

Usually that isn't much more hassle than just tagging it, unless there are merge conflicts to resolve (which get more likely the more the development branch diverges from the latest release branch). In that case there is the temptation to postpone the cherry picking, which, as mentioned, has the potential of being forgotten.

Tagging something for inclusion in a bugfix release however is always easy. Of course, usually you only think of that when fixing something which is an obvious candidate for a bugfix release, and tend to forget all the small bugfixes.

All in all I think the approach you suggested would be (far) more efficient, but we need to get used to it first. Implementing a new policy like takes time and effort, not because it's so complex and difficult, but because it's hard to break old habits. Getting all contributors to do their part for this to work needs some persistent prodding, herding, nudging and looking after, which I fear would be my responsibility (as release manager), and right now I simply don't have the time for that.

I'm currently swamped with private/personal and job issues, I have to focus on the most essential of my "duties", so to speak. Hopefully my situation will get better in a few months, then I can start experimenting again... :wink:
