### ISSUE TITLE
Crash when loading saved games

### ISSUE THREAD

**Issue by subpop** [freeorion/freeorion#2406]
### Environment
* **FreeOrion Version**: 0.4.8
* **Operating System**: Linux
* **Graphic card used**: AMD
* **Fetched as**
  * Compiled from source

### Description
Downstream Fedora package maintainer here. I received a report of a crash when attempting to load saved games, and when attempting to save a second game. The stack trace can be viewed here:

https://retrace.fedoraproject.org/faf/reports/2382880/

It looks like there's a crash caused by Boost when trying to read existing .sav files.

Edit: we're compiling against Boost 1.66 in Fedora right now.

### Expected Result
The Load Game dialog should open.

### Steps to reproduce
1. Save a game
2. Click "Load Game"

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1665748

**Comment by subpop** [comment]
Could it be that the sav file is XML and the stack trace appears to be using `binary_iarchive`?

**Comment by o01eg** [comment]
It looks like same bug as https://github.com/freeorion/freeorion/issues/2365 fixed in https://github.com/freeorion/freeorion/pull/2366

**Comment by subpop** [comment]
Sure does! I'll try to backport that patch.

**Comment by Vezzra** [comment]
@subpop, if backporting #2366 fixes your bug, can we close this issue as resolved?

**Comment by bernhardu** [comment]
Another downstream bug got reported [here](https://bugs.debian.org/930417) for debian.

There I thought first #2365/#2366 would be the solution.
But now I think this bug is not a duplicate of #2365/#2366.
Instead this one seems already be solved in commit https://github.com/freeorion/freeorion/commit/3e840f8d747fd0e6a513f3ef0278d3931f813109.

At least the backtrace I found in the debian bug and
that in retrace.fedoraproject.org seem to be similar.

**Comment by subpop** [comment]
I patched 3e840f8 into my downstream 0.4.8 package and it no longer crashes.
