### ISSUE TITLE
AI do not send further more invading ship after invading fails.

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2532]
AI has occupied one of my stars, then he sent a landing fleet. 
For some reason, he failed, that star still has 10 defense left. 
Well, from then on, he never send new land ship, he has more than 100 landing unit of landing ships in his home star. 
He just stay there and let my star burn his fleet ( I have burn enemy ship tech researched ). 
After about 10 turns, I take my star back.

This happens many times. 

My version is : 2019-08-04

**Comment by geoffthemedio** [comment]
Why closed?

**Comment by Morlic-fo** [comment]
Your feedback on AI behavior is very helpful but I generally need a testcase (i.e. savegame) to see what the issue is and to verify changes. If possible, please always try to create a savegame and upload it when creating an issue.

So, if you still have the savegame, I will happily take a look at it and try to implement some improvements.

**Comment by jinlan** [comment]
I closed this because I played a new game and AI has sent new invading fleet. 
So this is accidental. Human also sometimes make wrong decision.

But it will be good if it never happen.

Sorry, autosave is lost.
