### ISSUE TITLE
[release-0.4.5] Too many information at startup SitRep

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#254]
I start game and see a lot of  messages in SitRep.

I think It will be better to replace all colony entries with one custom message or just remove them.  

`Imperial palace has been unlocked and can now be produced`  can be replaced with `Imperial palace established at <planet>`
![big_sitrep](https://cloud.githubusercontent.com/assets/171597/8918061/6cbdc838-34be-11e5-9d42-0af2a27c1676.png)

**Comment by Dilvish-fo** [comment]
I can understand the concern, although I think the path to explore for a solution would be different, and even then I'm not really convinced it should be changed.

The code that makes those entries is general purpose and we don't really want to bake specific content references into it.  We could use an  initial-turn-exclusion-list from "common_user_customizations.txt", but I don't think it would really be best to suppress all these.  I think you're overlooking the fact that you're already familiar with all these; for a newcomer to the game it actually might be quite helpful to have these handy links to click on and get an idea what is available that way.

If we were to change it, I think the way to do so would be to leave all these unlocking messages in their current spot (which is for turn -32000 or so, which gets displayed as "Initial Turn", but add parsing and whatnot so that the two intro sitreps could be set to Turn 1, and have the SitRep panel be initialized to turn 1.  So the two intro messages would be visible, and you could see all these others by going back one turn.  There is a SitRep constructor that takes a turn parameter, but we might need to change it a little, and the GenerateSitRep Effects has neither parsing nor current parameters for that.  So I think that's all too much to do for 0.4.5 at this point-- the time to raise this kind of issue was a week ago.  I also am not at all convinced that we really want to hide/suppress these, even in this lesser manner.

**Comment by Cjkjvfnby** [comment]
I see a lot of unusefull information.  Newcomer come to play game, not to read about game for hours.

I am sure that nobody will read more then 2 `<Race> colony building` sitrep.  Because it has same text.

Basically I don't like idea to have some default techs (default for all empires)
Info about researches that sets initial bonuses can be squashed to one message.  
Info about researches that unlocks part can be skipped (we already have sitreps for parts)

> the time to raise this kind of issue was a week ago.

I don`t  know nothing about release schedule, can you point me to corresponding thread?

PS. If you don't plan to fix It to release, please rename it and add corresponding label.  If you not convinced about if this should be done, please close this ticket.

**Comment by MatGB** [comment]
I'm inclined to agree that having all the colony buildings listed isn't ideal, but **everything** else should be there as a new player will be able, even if they're not interested immediately, in looking at what various things do.

But the timings for the release has been discussed for some time, it's been delayed a week already as heavily discussed, it's in the planning for 0.4.5 thread.

All the colony buildings is annoying, but I'm not sure how it can be avoided without significant coding, it's better to have it there than not, need to ensure they're all at the bottom though.

**Comment by Dilvish-fo** [comment]
> need to ensure they're all at the bottom though.

Well, conveniently, they _are_ all at the bottom, right?  At least for me they are.

> All the colony buildings is annoying, but I'm not sure how it can be avoided without significant coding, it's better to have it there than not

Making an additional message that covers all these (maybe one for the initial techs, one for initial parts/hulls, one for initial buildings) would be easy enough.

As for suppressing these, to expand a little on my idea above, one reasonable way to make a change here could perhaps be to have a "permanently dismissed SitReps list' in the common customizations file; these colony building SitReps could be there, and perhaps even these part/hull unlocking messages.   The extra bit of code to support just a simple list like that would be pretty minor.  The bigger challenge for it would be to handle it in a way that also works for people  not using English.  We'd probably need a more special purpose list that alternated template1, part_tech_whatever_1, template2, part_tech_whatever2, etc.  That is seeming a little kludgey, but maybe reasonable, if we really did care that much about suppressing these.  I'm not thinking I do.

**Comment by Deepsloth** [comment]
Here i also agree with Cjkjvfnby. I have never read a book about game design, but i'm sure they all agree about not unloading dozens of articles on a new player right away.

Imagine yourself starting a new game and being confronted with lots of text to read up-front. You will probably skip it, because you want to play (i would), but a little nagging feeling will remain that you should have read it, which makes you uneasy.

**Comment by Mitten-O** [comment]
I tried #260 and I very much like the cleaner initial sitrep dialog. The player will be able to read up on the techs and buildings they have from the tech, design and production screens, so making the initial messages a bit more hidden shouldn't be a problem. A mention about the back button giving access to this information can be added to some of the instructional material somewhere, if necessary.
