### ISSUE TITLE
Pedia gives incorrect information for fuel of a hull

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#2541]
Since #2492, the pedia description of hulls is incorrect as far as fuel is concerned. 

1) For example the [basic small hull](https://github.com/freeorion/freeorion/blob/master/default/scripting/ship_hulls/SH_BASIC_SMALL.focs.txt) has base fuel 2. That is also the value which appears in the pedia. Effectively, however, the hull has 8 fuel due to the ```[[GREAT_FUEL_EFFICIENCY]]``` effect.

2) The fuel efficiency of a hull is never mentioned in the pedia.

This makes it impossible to figure out how much fuel the hull actually has (or how much adding a fuel pod will help) from the pedia.

Expected result:
Show fuel efficiency for all hulls with the corresponding scaling factor.

Probably preferably, the fuel after fuel efficiency applied is presented to the player. The alternative, showing base fuel only and then letting the player do the calculation seems rather clumsy. In that case, there should be rewording or an additional sentence to make clear that the base fuel of the hull will be multiplied by the fuel efficiency factor.

**Comment by agrrr3** [comment]
Already started discussing documentation issues and solutions in [Forum thread](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11321#p96865)

**Comment by alleryn** [comment]
@Morlic-fo I'm attempting to address some of your concerns via https://github.com/freeorion/freeorion/pull/2596.  This would correct the fuel value in the Pedia for the hulls, but won't explicitly state the Fuel Efficiency for each hull.  (My understanding is there are concerns over accessing the FOCS files from the C++ code in order to do this -- see https://www.freeorion.org/forum/viewtopic.php?p=97692#p97692)

Thoughts on this approach?

**Comment by geoffthemedio** [comment]
> won't explicitly state the Fuel Efficiency for each hull.

This can be added to the hull's description text in the stringtable.

**Comment by Vezzra** [comment]
Fixed by #2621.
