### ISSUE TITLE
'Ghost' colony renders planet unusable

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2556]
### Environment
* **FreeOrion Version**: 09 Sep
* **Operating System**: Win 7
* **Graphic card used**: RadeOn 5750
* **Fetched as** 
  * Binary release
  * Weekly development build

### Description
When my opponent conceded, his pops vanished but all his buildings remained. One of them, at an outpost, was a completed Exobot colony, which had been built but not used up. I cannot scrap it, and I cannot build an exobot colony of my own. 

### Expected Result
The completed colony building should activate and create an exobot pop.

### Steps to reproduce
Conquer your enemy until he quits in between the turn that a colony completes and the turn it activates.

**Comment by agrrr3** [comment]
I would rather expect all the colony buildings to be removed exactly like the population of planets is. But this might be too complicated/not worth to implement.

Also I would expect the building to be scrapable.

**Comment by magnate** [comment]
Yes I would expect those too. My original expectation was in the sense that given that neither of those things happened (it did not disappear and is not scrappable), I would expect it to activate.

**Comment by agrrr3** [comment]
According to the FOCS implementation the colony building should self destruct. If that is not the case, could it be that effects are not applied for conceded empires(???). The other explanation would be that the CreationTurn of the building got messed up on concede.

**Comment by magnate** [comment]
Incidentally the building has now disappeared, a dozen or so turns after I took the belt, but I still cannot built an exobot colony building there.

**Comment by agrrr3** [comment]
Please upload a save game

**Comment by magnate** [comment]
I will soon - we've just finished the game so o01eg is going to make all saves available.

**Comment by o01eg** [comment]
There all saves you need https://freeorion-test.dedyn.io/fo-saves.7z

**Comment by geoffthemedio** [comment]
> According to the FOCS implementation the colony building should self destruct. If that is not the case, could it be that effects are not applied for conceded empires(???).

Capture results apply when capturing a planet using troops, not when colonizing an unowned planet. When colonizing, it should assign ownership of all buildings on a planet to the colonizer. Since it was mentioned that the population of the planet was removed, presumably this is a recolonization or outposting, not a capture with troops.

@magnate did you own the building after colonizing the planet?

I don't know why the building would disappear after several turns, though... Was the building visible? Maybe it was actually already gone but the client didn't understand this and just left its last known / seen state in the UI, like a previously-seen fleet, until the info was considered stale?

What I can do is make conceding also destroy all the buildings of an empire... edit: https://github.com/freeorion/freeorion/commit/4ccd153c0f90533dfd477a8ef0b1b4d79d6b824f

**Comment by geoffthemedio** [comment]
@magnate Is this effectively fixed now? In my tests, conceding empires' buildings are now all removed, along with their ships and population...

**Comment by magnate** [comment]
Sorry, I didn't see this reply. I think what happened was that the colony was built the turn O01eg quit, so the building had already been activated. I've never really understood why it's shown on the turn it's been activated and created the colony, but it explains why it couldn't be deleted as it had already gone. It did eventually disappear many turns later (possibly after a server upgrade). Will look out for it happening again.
