### ISSUE TITLE
AI and players can mount engines in base hull and send them travel starlanes

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2882]
### Environment
* **FreeOrion Version**: v0.4.9+ b2112fe

### Description
AI can mount engines in base hulls and send them to travel starlanes.
[Forum thread](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11625&p=100920).

@Morlic-fo 

### Expected Result
This can't happen.

### Steps to reproduce
There is a save game posted in the linked thread.

**Comment by agrrr3** [comment]
That is not necessarily a bug (and the I knew you could build a base hull colonizer - just did not think the AI would build one).

It would be a bug in the AI ShipDesigner if there are cheaper and better (faster/sturdier) designs available at the building place. But there may be a rare situation where you do not want to wait for a shipyard to be build, so even the base hull colonizer has a niche.

Before this design was not possible, because you needed at least two internal slots to make an immobile hull movable - one for the colony pod, one for the engine and either one for fuel tanks or the right tech/species for some fuel.

**Comment by Oberlus** [comment]
Base hull designs are described in the stringtables as "can't travel starlanes".
/Edit: and that is still true since those ship designs don't have engines mounted./

Base hulls in general are expected (maybe just implicitly) to not be inter-system ships.
/Edit: Or not. We can just edit base hull description to account for "unless better engines are mounted" or something like that/

~~I think that should be maintained for balance purposes.~~ Edit: I changed my mind.

Can engines be forbidden into base hulls (for human and AI players) FOCS only?

**Comment by Oberlus** [comment]
@swaqvalley tested this for official v0.4.9 release and it is also affected.

So there was never in place a mechanic to avoid this behaviour. I'll continue debate in the forum thread.

**Comment by Oberlus** [comment]
Debate in the chat room: @l29ah @swaqvalley and ThinkSome do not see it as game-breaking.
L29Ah also liked the idea of having more choices at game start.

**Comment by Morlic-fo** [comment]
> Can engines be forbidden into base hulls (for human and AI players) FOCS only?

Yes, you can use ```exclusions``` keyword.

**Comment by Oberlus** [comment]
It seems no body has an strong opinion on this matter. @swaqvalley noted in the forum thread that it makes more sense to not allow this unintended mechanic because it's not easy to explain to new players, makes little sense regarding current hulls and techs descriptions, and would be seldom the right choice to build.
Moreover, the fix is simple (FOCS only, so players could change it on their own) and the AI issue is already tackled by PR #2886.

My vote is to merge the linked PRs and close this issue.

**Comment by Vezzra** [comment]
Seconded, and I think it should be in the 0.4.10 release.
