### ISSUE TITLE
Flickering credits text

### ISSUE THREAD

**Issue by rixxster** [freeorion/freeorion#289]
The scrolling text shown under credits are flickering when running on ubuntu 15.04
with v0.4.4[SVN 7640] of the game.

**Comment by Vezzra** [comment]
The version you're using is a year old and _very_ outdated. We've migrated to SDL2 since then, so the issue might be gone. We're very close to release 0.4.5 these days, the first release candidate will likely be ready at the beginning of next week.

If you can try again with a new version once it's available on your platform ([or you can try to build FO yourself](http://freeorion.org/index.php/Compile_In_Linux)), please report back if the issue persists.

**Comment by geoffthemedio** [comment]
I've tweaked credits to scroll by whole pixels instead of fractional pixels. This seems to reduce the "flicker" for me.
