### ISSUE TITLE
Buggy influence modifiers on natives

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3136]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 0.4.10+ 0b407ff
  * Compiled from source
* **Operating System**: Ubuntu 18.04
* **Graphic card used**: GeForce 860M

Description
-----------

Natives seem to have some kind of undocumented/buggy malus to influence, they have repeated instances of "Species <natives> -1":

Turn 10, just conquered:
![native_influence_malus_10](https://user-images.githubusercontent.com/28650914/89763667-45223800-daf3-11ea-9b45-7c86ed177958.png)
Turn 11:
![native_influence_malus_11](https://user-images.githubusercontent.com/28650914/89763674-481d2880-daf3-11ea-9562-a9a6b67ad08c.png)
Turn 12 (and following):
![native_influence_malus_12](https://user-images.githubusercontent.com/28650914/89763681-4a7f8280-daf3-11ea-92d3-a2728d88564a.png)

When you colonize a world with natives (i.e. it is not a homeworld for that species), the -1 influence effect appears one less time (so twice on turn of colonization, two times again on the following turn with the text changed to "Unknown" for the second one, and finally only once in the following turns).

When playing with Supertesters, the second malus on colonies or third on homeworlds (the one that becomes "unknown on second turn after acquisition and disappears on third and following turns) does not appear at all, so it seems to be some kind of misunderstanding on the client side, maybe.

So in the end there is -1 influence malus for every colony (including capital or starting species) and one additional -1 malus to native species homeworlds.

**Comment by geoffthemedio** [comment]
These are influence costs for having colonies. They need accounting labels set but are mostly working as intended except for the unknown factor on the first turn.

Species homeworlds cost a bit more influence to control because they are more inclined to want to control their own home planet. Could be made a stability penalty instead, though.

I think there are also some effects related to whether planets are supply connected to the capital or by how many lane jumps they are distant from it.

**Comment by Oberlus** [comment]
Solved by https://github.com/freeorion/freeorion/commit/ed804c79332ef3039c6ef376c868cb0e293cfb30
