### ISSUE TITLE
Named Values in Tooltips Missing

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3268]
As mentioned [here](https://github.com/freeorion/freeorion/pull/3240#issuecomment-749163409) named values in tooltips are missing. 

![102815828-521e3480-43cd-11eb-82c5-2c062def66c7](https://user-images.githubusercontent.com/11386908/103412229-5cca8d80-4b74-11eb-8e30-1add87c70372.png)

**Comment by Vezzra** [comment]
> Reportedly doesn't occurr on OSX.

Sorry, correction, it definitely does occur on macOS.

My bad, I've been confused - because the screenshot doesn't show the entire tooltip box, I thought the issue was that word wrapping was broken (which would have been a completely unrelated issue).

The numbers are missing on my Mac as shown in the screenshot.

**Comment by agrrr3** [comment]
After code analysis. Yes, the tooltips there created as CUILabels in IconTextBrowseWnd::PreRender() and currently valueref support is only in LinkText.

CUILabel is basically a wrapper around a GG::TextControl, so I guess that textcontrol strips the tags away.
So where to hook the valueref support in? First thought: put it into all CUILabel rendering. 

edit1: i implemented something more local/simple
