### ISSUE TITLE
CMake:  Wrong libdir when installing on some systems/archs

### ISSUE THREAD

**Issue by raptor** [freeorion/freeorion#333]
Running `make install` on some systems (e.g. openSUSE x86_64) will use the libdir of `lib` instead of `lib64` like it should.  
I can currently work around this by running a CMake command with the `LIBSUFFIX` variable like this:

```
cmake -DLIB_SUFFIX=64 ..
```

I think the proper way to fix this is to use the interal CMake variable `%{CMAKE_INSTALL_LIBDIR}` in the install portion of the game instead.  This variable properly picks up the system libdir, whether it be `lib32`, `lib`, or `lib64`, etc.

**Comment by raptor** [comment]
For reference, here is how I build freeorion for openSUSE (build commands start about line 80):
https://build.opensuse.org/package/view_file/games/freeorion/freeorion.spec?expand=1

**Comment by hean01** [comment]
The proper way would probably be to include GNUInstallDirs on linux builds, this will set LIBDIR to correct path respecting lib / lib64 and lib/x86_64 (debian)...

https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by Vezzra** [comment]
@adrianbroher, as you seem to be back and active (at least for a while?), I've assigned this issue to you - you probably know best what changes need to be made to the cmake files to address this issue/request.

Is that ok? Otherwise feel free to un-assign yourself...

**Comment by adrianbroher** [comment]
Sorry that fixing this took this long.

@hean01 
Thanks for pointing out the `GNUInstallDirs`, I knew about that before but never bothered to look into it. It made the whole thing a lot easier.

@raptor
Could you check if the current implementation is sufficient for your needs?

Also I've seen that you disabled RPATH for FreeOrion.  While it is generally right that RPATH is frowned upon I would like to point out that our usage of RPATH doesn't violate any known rules for packaging for [Fedora](https://fedoraproject.org/wiki/Packaging:Guidelines#Rpath_for_Internal_Libraries) or [Debian](https://wiki.debian.org/RpathIssue#Debian.27s_Stance), because those (private) libraries are not intended to be shared at all with other applications. So the statement 

> forbidden by red hat

isn't true and removing RPATH just to install a `ld.so.conf.d` is quite pointless.

**Comment by raptor** [comment]
Hi, thanks for supporting this.  That comment in my SPEC file regarding RPATH was made a long time ago (probably with freeorion 0.4.3) and I don't remember the reasoning at the time - packaging rules may have been slightly different.  Thanks for investigating and finding that it doesn't apply anymore.  I'm actually surprised fedora still doesn't seem to have a freeorion package built from someone in their community.

I'll update the package and test your changes when I can, hopefully soon.

**Comment by raptor** [comment]
I've confirmed that this is sufficient for packaging with 0.4.6 RC1.  Thanks!
