### ISSUE TITLE
Build system has extremely high memory usage

### ISSUE THREAD

**Issue by crabctrl** [freeorion/freeorion#3330]
I understand that this may or may not qualify as a "bug", but I thought I'd mention it regardless. Attempting to compiled freeorion with four threads immediately results in all 6GiB of my system memory being used, followed by the build failing. This is a pretty enormous amount of memory.

Of course, if there's some reason it does this, there's nothing to be done. However, if the build system could be modified to result in more reasonable memory usage, I feel it would make the game significantly more accessible. Currently I have to build using only one thread, which still results in almost 2GiB of memory usage.

**Comment by geoffthemedio** [comment]
High memory usage is usually due to compiling the parsers, which make use of a lot of template-heavy Boost stuff. If you can reduce the parallel builds just for that project, it should be sufficient to limit the memory use. Otherwise this can't be fixed without replacing the parsers with a different implementation.

Marking Won't Fix, though @o01eg is working on an alternative parser.
