### ISSUE TITLE
GUI Planet Textures are missing/not shown

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3354]
Bug Report
==========
i think i noticed this before, but wasnt really paying attention. Now that i tested the latest snap, the planet textures are not applied.

Environment
-----------

* **FreeOrion Version**:  weekly-test-builds-2021-03-09; 7b53534209a41e8a0829f9d2e5f79b1cd7e8af1c 
* **BUILD**: current weekly snap

Description
-----------
Planets look bland. Textures are missing. E.g. desert planet looks like a yellow ball.

Expected Result
---------------
The planets images should have textures and should "turn".

Steps to reproduce
------------------
Start a game.

**Comment by geoffthemedio** [comment]
Broken in 6ea05a8deab83149e55765f0aa6b0fb94c2685c8
Broken in fbabb59306cb8c9e71d12d8ef7e6d336c254cdcb
Broken by 0bc9cc995004cb3fde9b030235e3f5611d3266d2
Working in 864ec4b41ada27d74b3ae1d6aeb27c7e1986b8f0
Working in 4e314f3b5f86a3b984a55fc78c74524b8ffa8854

should be fixed by https://github.com/freeorion/freeorion/commit/29e9e12b0af99332192d14432dbbf44347e3fc32
