### ISSUE TITLE
Ancient Ruins research and regular research clash

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#343]
Death Ray 1 research target is left over in research list.

I researched Death Ray 1 in the same turn as I got it from an Ancient Ruins. The Situation Report first reported "Death Ray 1 was revealed in the Ancient Ruins!" and a few lines below "Death Ray 1 has been researched."

Now, Death Ray 1 still is present in my research queue, with the projected target turn of "never". I already researched further Death Ray technologies. I cannot move "Death Ray 1" in the queue. It simply stays at the same position. I can drag other technologies above or below and the position changes accordingly. Finally, I manually removed Death Ray 1 from the list.

What I like to propose:
- If regular research finishes in the same turn as an Ancient Ruins revelation, do not consider this technology as available for the revelation.
- Or, if not possible or desired, at least automatically remove the technology from the research queue.

I am using master (de699b506aeee3bd24385f169ebb0c22a731069b).

**Comment by Dilvish-fo** [comment]
It looks to me like the fact that you finished researching DR 1 on the same turn as getting it from the Ruins is essentially a red herring here.  I just confirmed that if you have DR1 anywhere in your research queue on the turn that you get it from the Ruins (or any similar effect), then it winds up in the state that you describe; this has always nagged me a little, and so this issue is enough to get me to move on it.

I am about to put in a fix, a slight adjustment to the research queue update process to ensure that techs which have been completed are removed regardless of whether they were completed via research progress or via direct grant.

**Comment by aschuch247** [comment]
Okay, great. But what about the "race" between regular research and ancient ruins research? It still is possible to learn it "twice" in a turn? Site messages will contain the research twice as well then - once by ancient ruins and once by regular research?

**Comment by Dilvish-fo** [comment]
The award from the Ruins happens first, and any RP allocated to researching the tech that turn will be wasted, but my code review indicates you should not in that situation get a sitrep about researching the tech.  The fix to avoid wasting the RP  is probably not terribly difficult, but I think not really simple either; given the rarity of the issue it will probably be low priority for quite a while.
