### ISSUE TITLE
Gifting exchange should be possible

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3468]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2021-05-10.4f04bdc
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

Description
-----------

If two empires gift each other only assets in same system only one empire gets gift.

Expected Result
---------------

Both empires should exchange gifts.

Steps to reproduce
------------------

* Move two ships of each empire into system without other objects.
* Both empire should gift ship to other.
* Press turn.

**Comment by geoffthemedio** [comment]
Specifically if they both give all their stuff in the system?

**Comment by o01eg** [comment]
@geoffthemedio Yes

**Comment by Oberlus** [comment]
Hopefully fixed by Geoff's 95b4960, which is already merged if someone has the time to test it.

**Comment by geoffthemedio** [comment]
> ... if someone has the time to test it.

Please do...

**Comment by Oberlus** [comment]
I think this can be closed as solved.

I started a local MP game with two clients, moved one ship of each empire to the same system (so only one ship per empire in the system), gifted with one client and pressed turn, gifted with the other client and pressed turn, and the gifting was successful. I then repeated it with another two ships on a different (otherwise empty) system and worked again.
