### ISSUE TITLE
SitRep, scrollbars and resize

### ISSUE THREAD

**Issue by Szunti** [freeorion/freeorion#367]
Sorry, it seems I can't get over the scrollbars in SitRep.

After resizing SitRep a couple of times weird things can happen. Scrollbars range can get smaller than the content. (Missing a lot of lines at the end of text). Or even weirder, like this:

Scrolled to top (this is fine):
![fo-scroll1](https://cloud.githubusercontent.com/assets/1443881/10223835/6a2b222a-685b-11e5-8fea-7dceb7ede23c.png)

Scrolling with mousewheel once(still ok):
![fo-scroll2](https://cloud.githubusercontent.com/assets/1443881/10223850/78758d70-685b-11e5-8ca4-2fc4ca558600.png)

Scrolling with mousewheel again (same as before?):
![fo-scroll3](https://cloud.githubusercontent.com/assets/1443881/10223860/851a90a2-685b-11e5-99f7-78d0f53ac01f.png)

And scrolling to the bottom (why does this show the top?):
![fo-scroll4](https://cloud.githubusercontent.com/assets/1443881/10223879/9c5e4cf4-685b-11e5-90ba-6e28028663a8.png)

**Comment by geoffthemedio** [comment]
It shows the top because the scrollbar is positioned such that it's slightly past the range where it would show the top of the second entry in the sitrep list, but there is no third entry to show. Due to how the loop to find which row to show is written, it thus never finds a row that it can show, so defaults to showing the top.

It's set up to always show the top of a row at the top of a window.

**Comment by geoffthemedio** [comment]
I tweaked the ListBox row positioning code to hopefully fix the top when at bottom issue. I think it would only appear when the last row is unusually tall, which had never been the case before that relatively long message in the second sitrep was added, and even then only when it's horizontally compressed to be extra tall due to line breaks...
