### ISSUE TITLE
Problem saving game in 0.4.5? [32-bit arm port]

### ISSUE THREAD

**Issue by MagaTailor** [freeorion/freeorion#372]
After saving the game, resigning and terminating with a WM keyboard shortcut I got a broken save.

If that's some sort of a user error and the file got truncated while still being saved, I'd suggest adding a progress bar for save operations. 

I can upload the save file if it's actually a bug.

**Comment by Vezzra** [comment]
When exactly did you terminate the app? When you were back at the main menu? In this case I don't think that terminating via keyboard shortcut has something to do with the corrupted save.

Anyway, can you reproduce that behavior, or did that happen only once?

**Comment by MagaTailor** [comment]
This has happened once so far and I only noticed the following day so my recollection could be fuzzy. I believe I didn't terminate while still on the map screen but I could be wrong (definitely remeber consciously waiting for a few seconds somewhere).

However I got to something like 400 turns and was experiencing a huge slowdown. The save having grown to about 15M might have been the problem in that it was taking so much longer to generate (but not write = ramdisk)

**Comment by Dilvish-fo** [comment]
The problem was probably that the AI's had not yet submitted their orders; normally this will cause the save button to be disabled until they have done so, but I think there is a situation where if you click next turn and then open up the options before the midturn up-date has been received, then at that moment the game won't yet be waiting on the AIs orders and so the save button is currently not disabled, but if the midturn update then arrives before you actually save, then the savefile will be broken.  At least, I think the scenario is something like that.

So, I think there is a slightly broader set of circumstances that should cause the save button to be disabled; I'll bookmark this to look into it, but it may not be anytime soon.

**Comment by Vezzra** [comment]
Probably the same issue as in #451, so we can close this issue too now...? @geoffthemedio?

**Comment by geoffthemedio** [comment]
don't know...  I suspect an autosave can still be interrupted by killing the program mid-save.

**Comment by MagaTailor** [comment]
In my case it was a manual save. A caption like `Saving...` in the corner somewhere could come in handy :)

**Comment by geoffthemedio** [comment]
Issues #451 was a bit more specific, and required a relatively large / long game to occur. I don't think it would lead to a broken save, but rather would lead to an empty save and an error popup that the save failed.

**Comment by MagaTailor** [comment]
I think it can be closed as not specific enough but on some ARM devices (much slower than a modern x86 desktop), especially after a long game, the user might not even suspect saving got so much longer.

**Comment by geoffthemedio** [comment]
ok
