### ISSUE TITLE
Fighters shot doesn't line up with Fighters destroyed in Combat Log

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#3863]
Bug Report
==========
Fighters launched by enemy = 10
vs
4 Interceptors
2 Fighters
4 Flux Lances
1 Mu-ursh Flak Cannon(5 shots) + Flux Lance

4 Flux Lances damage 4 Fighters for 1 damage
Mu-ursh ship damages 4 Fighters for 1 damage, and 1 Fighter for 2 damage
4x Fighter attacks Fighter

7x Fighters were destroyed

Environment
-----------
20th Game Multiplayer
Version is 2022-05-09.3abfde4.
Turn 51 Sitrep
Combat at Levitt y

**Comment by o01eg** [comment]
Ask me to get save files for this game.

**Comment by geoffthemedio** [comment]
Perhaps one of the fighters was destroyed simultaneously by two attackers?

**Comment by MichaelCourtney** [comment]
> Perhaps one of the fighters was destroyed simultaneously by two attackers?

Possibly, though it didn't work that for fighters in previous versions

**Comment by o01eg** [comment]
Can we somehow distinguish fighters one from another?

**Comment by geoffthemedio** [comment]
> Can we somehow distinguish fighters one from another?

They all have IDs during combat, but they aren't recorded in the combat log events.

**Comment by Oberlus** [comment]
@MichaelCourtney is pretty sure fighter never soaked more than one shot in previous versions.
This would break combat balance. Fighters now need much more PD weaponry to counter.

**Comment by MichaelCourtney** [comment]
I'll try stable version tonight. There's a related targeting issue I'd like to check. Planets are absorbing a full rounds worth of incapacitation shots. My memory says they use to only absorb 1 shot.

**Comment by Oberlus** [comment]
> I'll try stable version tonight.

I was too curious to wait:
![fighters_do_soak_more_than_one_shot_per_boat](https://user-images.githubusercontent.com/28650914/171381966-b3d905a9-4fcd-4a5a-8f5f-59641c72aea4.png)

Fighters do soak more than one shot also in previous versions. Valid targets are not removed from the pool until end of bout.


> Planets are absorbing a full rounds worth of incapacitation shots. My memory says they use to only absorb 1 shot.

Same as with fighters and ships, planets that were valid targets at start of bout will be valid targets for all attackers during that bout.

**Comment by Oberlus** [comment]
Since this seems to be the standard combat behavior for all FO versions, I think it is not a bug.

Also, I think it is OK to allow (keep) fighters the same behavior than ships and planets, so I would not support a feature request to change it. I find it more intuitive that either no target can soak more than needed shots or all targets can soak more than needed shots.

**Comment by geoffthemedio** [comment]
> Valid targets are not removed from the pool until end of bout.

Does a single ship weapon with multiple shots, multiple separate ships attacking, or multiple separate fighters attacking work any differently in this regard?

**Comment by Oberlus** [comment]
> > Valid targets are not removed from the pool until end of bout.
> 
> Does a single ship weapon with multiple shots, multiple separate ships attacking, or multiple separate fighters attacking work any differently in this regard?

Doesn't seem so.
In the attached combat log, one of the sentries shot all three flak shots to one of the two fighters. The other sentry, processed after the first one during the same bout, attacks the two fighters (one is already more than dead, the other is intact).

**Comment by MichaelCourtney** [comment]
> Also, I think it is OK to allow (keep) fighters the same behavior than ships and planets, so I would not support a feature request to change it. I find it more intuitive that either no target can soak more than needed shots or all targets can soak more than needed shots.

You are either contradicting yourself here or being unclear. For fighters and planets to have the same behaviour as ships a change would be needed. Either fighters and planets would need to change to match ships, or ships would need to change to match fighters and planets.

**Comment by Oberlus** [comment]
What I mean is, currently, ships, planets and fighters that are valid targets are all put in a pool, and weapons get random targets from that pool. If something is a valid target at the start of a bout, before weapons start shooting, it is a valid target for all weapons capable of shooting at it till the end of the bout, regardless of how much damage they take.
Then, after all weapons have dealed damage to their targets, the targets that have been destroyed (any shot for fighters, zero or negative structure for ships, zero shields and defense for planets) are removed from the pool and won't be targetted next bout.
This means that fighters, ships and planets all can be overkilled.
If we make fighters not targettable more than once, for consistency, we "should" make all targets non-overkillable. Do we like this luck factor of several death rays shooting down the same corvette and leaving intact other ships? If so, I think we can also like the same for fighters. Otherwise, combats would be less random and more predictable.

**Comment by MichaelCourtney** [comment]
Yeah its looking like I'm getting confused about a bunch things. My apologises, if I wasted someone time. This can be closed I guess.

There is 2 seperate issue that maybe need looking at, every fighter in the combat log is called Fighter whether its Fighter no. 1, Bomber no. 7 or Interceptor no. 6

The 2nd is this

This mouse over on the ship is misleading - fighters destroyed:
![fighter 1](https://user-images.githubusercontent.com/43386669/171448438-e6add2a9-c76d-4581-bf65-1278a9cb7b35.png)

This mouse over on the fleet seems correct - _max_ fighters destroyed:
![fighter 2](https://user-images.githubusercontent.com/43386669/171448615-9d9663ca-ecfa-4769-954d-e6c722410200.png)

**Comment by agrrr3** [comment]
> This mouse over on the ship is misleading - fighters destroyed: ![fighter 1](https://user-images.githubusercontent.com/43386669/171448438-e6add2a9-c76d-4581-bf65-1278a9cb7b35.png)
> 

yes, intentionally saving screen space... (the structure damage is also not guaranteed)

Else it would be `Totals for 4 bout battle, Maximum Structure Damage: 360 / Maximum Fighters Destroyed: 1`
or  `Maximum totals for 4 bout battle, Structure Damage: 360 / Fighters Destroyed: 1`

On the original topic: i think once in the past we changed fighters to be (inconsistently) removed from the valid targets immediately because the main weapons were always massively overshooting on fighters and doing that multiple times increased that imbalance. In my opinion flak/interceptors/strikers/arc disruptors multi-shooting fighters is not a problem. It is possible we did this using targeting (by restricting the target pool to the set of non-destructed fighters), so maybe something broke there.

Did anybody check in 0.4.10?
