### ISSUE TITLE
Augmentation description/effect mismatch

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4864]
Bug Report
==========

In the pedia it claims to slow down growth at low infrastructure and speed it up at high infrastructure.

However in misc.macros it has a growth rate equation that will always return > 1

**Comment by geoffthemedio** [comment]
Could you elaborate or at least link to the relevant script?

**Comment by MichaelCourtney** [comment]
![Aug](https://github.com/freeorion/freeorion/assets/43386669/43b61dae-b1dc-4e8d-a6b0-61a6204936f9)
Increase or decrease population growth, dependent on whether a planet's infrastructure is above or below 40
Testing in-game shows an increase in population growth at infrastructure = 1

https://github.com/freeorion/freeorion/blob/master/default/scripting/macros/misc.macros#L63-L64
or same in python:
https://github.com/freeorion/freeorion/blob/master/default/scripting/macros/misc.py#L67-L81

returns a growth rate of 1.5x - 2.2x depending on infrastructure. If I was to guess the intended values I'd suspect its meant to be 0.5x - 1.2x growth

**Comment by MichaelCourtney** [comment]
Note: I know how to fix this, but doubt the intended effect was well thought out.

Slow pop growth below 40 infrastructure, is in practice all colonies below 40 turns in age?

**Comment by MichaelCourtney** [comment]
One possible solution is to fix it, then look at ways to increase infrastructure growth?

**Comment by geoffthemedio** [comment]
The effect isn't well balanced, certainly. In general, infrastructure needs some attention to make more meaningful. It isn't meant to be just effectively a count of colony age, but rather of how developed a colony is and how much spare development is not consumed by supporting other activities on the planet. That can be partly about ways to increase infrastructure growth, but it would also be about ways to reduce or increase the infrastructure cap. One aspect of that is buildings consuming (and requiring) infrastructure, but it would also need some additional interactions to be more interesting... The infrastructure policies, for example, should be possible to make do something more interesting. And perhaps developing infrastructure instead of generating PP and RP could be a choice to some degree, perhaps on a per-planet basis, though that risks being to micromanagy...

**Comment by MichaelCourtney** [comment]
Ok, I've got a fix that I'll test then push and I'll just assume it'll be re-balanced when infrastructure gets taken care of.

> And perhaps developing infrastructure instead of generating PP and RP could be a choice to some degree, perhaps on a per-planet basis, though that risks being to micromanagy...

Perhaps policies could take care of the distribution. Bootstrapping pushing growth on new colonies, centralism the central colonies, industrialism the industry focus colonies, metropoles the metropoles...

**Comment by MichaelCourtney** [comment]
relevant thread:

https://freeorion.org/forum/viewtopic.php?t=12924&sid=f5cb5da6750bc69270500f88bcf7255c

**Comment by Vezzra** [comment]
@MichaelCourtney, with #4865 merged, can this be closed as resolved?
