### ISSUE TITLE
Can not launch test build on macOS.

### ISSUE THREAD

**Issue by magnusviri** [freeorion/freeorion#4872]
Bug Report
==========

Can not launch test build on macOS. Crash log:

````
dyld[9916]: Library not loaded: /usr/local/opt/libogg/lib/libogg.0.dylib
  Referenced from: <636480D9-376F-3048-93A8-35ACEC79A7F9> /Users/james/Downloads/FreeOrion.app/Contents/MacOS/FreeOrion
  Reason: tried: '/usr/local/opt/libogg/lib/libogg.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libogg/lib/libogg.0.dylib' (no such file), '/usr/local/opt/libogg/lib/libogg.0.dylib' (no such file), '/usr/local/lib/libogg.0.dylib' (no such file), '/usr/lib/libogg.0.dylib' (no such file, not in dyld cache)
zsh: abort
````

I have no /usr/local/opt.

Environment
-----------

* **FreeOrion Version**:
  * FreeOrion_2024-02-14.395bd4c_Test_MacOSX_10.15

* **Operating System**:
  * macOS 13 Ventura

* **Graphic card used**:
  * M1

* **Fetched as** 
  * Weekly development build

Description
-----------

It doesn't launch

Expected Result
---------------

It should launch

Steps to reproduce
------------------

Download weekly build. Mount dmg. Copy file from disk image to drive. Right-click select "Open". Select "Open".

**Comment by magnusviri** [comment]
0.5 build doesn't have this problem.

**Comment by geoffthemedio** [comment]
@Cjkjvfnby @o01eg ?

**Comment by o01eg** [comment]
@geoffthemedio I have no idea how MacOS works. Maybe @Vezzra can check different weekly test build version?

**Comment by Vezzra** [comment]
I have checked weekly test builds back until August 2023. The last test build that worked was the one built based on c23eb382ed4896ac3b8eb276d15ccfb9a4a3c7b5, the test build of the following week, built based on 83125490c1767d365365ebb0591b70fa759a882c, crashes with the exact same error reported here.

However, this bug is an issue with the CI. When I build FO on my local system, everything works fine. Which also means that I can't further narrow down the commit which introduced the bug, as building on my system does not reproduce it.

Unfortunately there are quite a lot commits in master between these two. I quickly browsed through these commits, looking for ones that contain changes to the build scripts or anything that, to my eyes, looked like something that could affect the CI. The commits that caught my attention are:

- 04abba9951dcc49c8dc04d320e78307b48b4c594 "Test Python parsers on MacOS" by @o01eg
- dbecd7b4b5ea1fab713005061f7916844afa72f7 "Use FindPython3 CMake module instead of deprecated FindPythonLibs and FindPythonInterp" by @o01eg

Why one of those would cause the CI to link the wrong `libogg` eludes me. And of course it's possible that I missed the commit that is actually the culprit here.

But anyway, maybe that already can help someone more knowledgeable of the CI to fix the problem? @o01eg? Do you think you can work with that from here?

**Comment by Vezzra** [comment]
As far as I can tell, the problem is that the CI build process links the wrong `libogg` dynamic library. Instead linking the one of the Ogg framework shipped with the app bundle (located in `FreeOrion.app/Contents/Frameworks/Ogg.framework/`), it finds some other installation of `libogg` (located in `/usr/local/`) and picks that to link against.

Which of course leads to the error reported here when the resulting FO app is launched on a different Mac system, unless that system (for some reason) contains the same `libogg` installation in the same place.

**Comment by o01eg** [comment]
Looks like that line broke `libogg` search:
```
set(CMAKE_FIND_FRAMEWORK "LAST")
```
It works globally while I had intention to switch only Python search.
