### ISSUE TITLE
Situation Report lists wrong system

### ISSUE THREAD

**Issue by magnusviri** [freeorion/freeorion#4873]
Environment
-----------

* **FreeOrion Version**:

0.5

* **Operating System**:

macOS 13 Ventura

* **Graphic card used**:

M1

* **Fetched as** 
  * Binary release

Description
-----------

For some reason the Situation Report says there's a ground battle when there should be none.

<img width="500" alt="Screenshot 2024-02-24 at 17 35 24" src="https://github.com/freeorion/freeorion/assets/711269/0897b1d4-2626-411d-b53a-d1d8f4f7a8d0">

I do have a warship in a system of another player, but that planet is not visible. So if I understand the rules, that means there isn't a ground battle there.

<img width="519" alt="Screenshot 2024-02-24 at 17 35 36" src="https://github.com/freeorion/freeorion/assets/711269/1d22fde8-4829-48be-992b-0a9af1c741f3">

Expected Result
---------------

It shouldn't say there's a ground battle.

Steps to reproduce
------------------

I'm including a save file.

[save-20240224_173238.sav.zip](https://github.com/freeorion/freeorion/files/14394875/save-20240224_173238.sav.zip)

**Comment by agrrr3** [comment]
well, your game is at turn 17 and the report is from turn 14 (the screenshots match the save game at turn 17)

i guess you blocked some kind of messages (as one can see your sitreps are pretty empty); there is some functionality to help you see the relevant messages. i thought it skips to the last report which contains a visible message, but it actually restricts one from accessing that turn's sitrep 

so that might be considered a bug/bad interface

for your  game, i would consider unblocking some messages

guess it is either rephrase the issue or close

**Comment by magnusviri** [comment]
Yeah, I realized after I deleted all the auto save games that I should've kept the auto save for turn 14.

So I'm not sure I understand. Was there a blocked message that would've explained the attack? Or did I just get confused while playing the game?

**Comment by MichaelCourtney** [comment]
Hard to tell without a save for turn 13. My guess is you had negative stability on the planet on turn 13 and rebel troops

**Comment by Vezzra** [comment]
As it's not really possible to investigate this issue without a save, I'm going to close this ticket. If the issue turns up again, and you have a save, feel free to reopen this issue or open a new one.
