### ISSUE TITLE
Can't Drag-Drop a Policy Over Another

### ISSUE THREAD

**Issue by tkrypton** [freeorion/freeorion#4883]
* **FreeOrion Version**: v0.5
* **Operating System**: Linux, Devuan daedalus (Debian 12 without systemd)
* **Graphic card used**: [AMD/ATI] RV710 [Radeon HD 4350/4550]
* **Fetched as** 
  * Compiled from source

Hi,

apologies if this is a known bug, but I haven't found it - neither as open nor as closed issue:

Either I'm too stupid or policy adaption on Linux is broken. I can choose and adapt a policy when it is the first one of it's type by drag & drop just fine, but I can't replace it this way. I've tried to double click the policy I want to adapt, but that did not work either. The ones I've adapted first are staying active.

I would appreciate pointers to the code which handling that part of the UI, maybe I'll be able to debug it,

CU,
Uli

**Comment by agrrr3** [comment]
Hi, for the stable 0.5:
I can confirm that drag-n-drop on an existing policy does nothing (this is
a bug).
Double-clicking a policy fills an empty slot, but does not replace any
(this is certainly intended).
I think the reason that not everybody complains is that you can remove a
policy by double-clicking. And then you can fill the empty slot (by
drag-n-drop or double-clicking) (this could be considered a workaround in
relation to the bug).
Can you confirm?

**Comment by geoffthemedio** [comment]
Due to how policies can have dependencies, replacing in a slot is reasonably not supported. Rather, one needs to free a slot and put a policy into it, so there is no ambiguity about what happens when replacing. eg. if I drop a policy onto another policy that it has as a prerequisite or exclusion, should that work? what if there is a cost dependence on the order of doing it? what if there are also other free slots that could have been used; should it act as if they were? etc.

Relevant code:
https://github.com/freeorion/freeorion/blob/master/Empire/Empire.cpp#L155
https://github.com/freeorion/freeorion/blob/master/UI/GovernmentWnd.cpp

**Comment by tkrypton** [comment]
OK, understood. Yes, I can confirm that removing a policy and then filling the empty slot again does indeed work. Wasn't obvious to me and I havn't found any help text about it except in the quick play guide, which only mentions double clicking.

I think it would be just fine as it is with a help text popping up when double clicking on a policy would not apply it.

Just my 0.02 €,
CU,
Uli
