### ISSUE TITLE
[AI] return universeObject.name as unicode

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#492]
If name contains greek letters it is returned like that  `Plato \xce\xb2 III` and prints as `Plato β III`

In case that we want to print text to log like in tables we will have broken aligment.

I tested it on **windows**, may be other platforms have different behavior

Here is some example code:

``` python
a = 'Plato \xce\xb2 III'  # str with greek like it returned in game
b = a.decode('utf-8')     # unicode
c = 'Plato B III'         # str without greek

print len(a), len(b), len(c)
> 12 11 11
print a, b, c
> Plato β III Plato β III Plato B III
print [a, b, c]  # still need to avoid of print it in lists
> ['Plato \xce\xb2 III', u'Plato \u03b2 III', 'Plato B III']
print '%-15s planet' % a
print '%-15s planet' % b
print '%-15s planet' % c
> Plato β III    planet
> Plato β III     planet
> Plato B III     planet
```

PS you can find example in log after string `System Threat Assessments`

**Comment by Vezzra** [comment]
I assume you want the backend C++ code adjusted so that the interface functions returns unicode, right?

I've to admit that I don't really know how to do that... that will require some research first.

**Comment by geoffthemedio** [comment]
The C++ code mostly already uses UTF-8 strings, so I'm surprised the Python API doesn't already provide UTF-8 strings. I suspect that it actually would on other platforms, but it's doing something different on Windows...

**Comment by geoffthemedio** [comment]
A bit of googling suggests something like this would do the conversion in C++, though I haven't tested:

```
    boost::python::object StringConverter(const std::string& input)
    { return boost::python::str(input).encode("utf-8"); }
```

**Comment by Vezzra** [comment]
Yes, found more or less the same already too. Will give it a try.

**Comment by Vezzra** [comment]
Ok, these are my findings after some fiddling around:

First, to get boost python to return unicode instead of string not `encode`, but `decode` needs to be used:
`return boost::python::str(some_string).decode("utf-8");`

Second, these creates issues if one of those unicode string thus obtained are subsequently passed to an interface function that expects standard strings (C++ signature std::string), which promptly throws a `UnicodeDecodeError` Exception.

So whenever `universeObject.name` is used you'd have to keep in mind that what you got is not a standard string, but a unicode string, and dependend on what you want to do with it, have to reencode. Which is going to complicate things whereever `universeObject.name` is used.

My question is, what for actually? @Cjkjvfnby, judging by the examples you provided, the strings returned by `universeObject.name` currently are printed out correctly anyway, the only case where we get weird results is if you print a list containing these strings. But in this case, the unicode strings are printed weirdly too, so what do we gain by returning unicode (besides extra hassles elsewhere)?

And if you really need them to be converted to unicode, can't you do that in Python by calling `universeObject.name.decode("utf-8")`?

**Comment by Cjkjvfnby** [comment]
`.name` is required only for one thing: print it to logs and nothing more. 

It printed ok, until you want to print it in table. In that case it looks a little ugly because real length and visible length is different.  If it is hard to fix, lets it be as is.  I will think how to solve it on python side.  

Thank you.
