### ISSUE TITLE
Assign priorities to Industry and Research resource output effects groups

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#547]
Refer to: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10006&view=unread&sid=96ccf93875079e58510e2de75d3978b7#unread

MatGB said:

> As for me, I'm currently working on:
> Um, oops, had completely forgotten about this project, just checked my old working branch, will need work with the recent splitup but needs doing.

**Comment by Vezzra** [comment]
@MatGB: do you want to include that in 0.4.6, or postpone for afterwards?

**Comment by MatGB** [comment]
I would like to get it in, I'm going to stop working on Fighters for a bit and go back to finishing this off, most of the work was done but I need to update it for the new split up scripting folders.

**Comment by Vezzra** [comment]
Ok, set milestone to 0.4.6.

**Comment by MatGB** [comment]
Industry done (I hope) with https://github.com/freeorion/freeorion/commit/d435b23ee42cb3cf5481fd1c0a690ee65b7c9e18 Add priorities and attempt to balance Industry modifiers, will almost certainly need feedback and tweaking. Research is next.

@Vezzra I don't know when you start prepping for the Test builds each week, I hope this isn't too late it was meant to go in yesterday but life got in the way.

**Comment by Vezzra** [comment]
Currently I usually start the test build production process on Tuesday late afternoon/early evening (UTC), unless RL interferes, then I try to do it at roughly the same time on Monday.

Which means, you've still some time left until the next test builds. ~20 hours as of the time of this post... 😉

**Comment by Cjkjvfnby** [comment]
Does scripting changes require build?

I setup my `persistent_config.xml` to get files from repo and does not depend on build. I hope that all devs do the same.  I don't know if we have users who use weekly builds but don`t have clonned repo.

```
<?xml version="1.0"?>
<XMLDoc>
  <resource-dir>f:\projects\FreeOrion\default</resource-dir>
  <stringtable-filename>f:\projects\FreeOrion\default\stringtables\en.txt</stringtable-filename>
</XMLDoc>
```

**Comment by MatGB** [comment]
Scripting changes don't require build, that's why I try to time stuff to be done by the end of a weekend so they'r ein a Test build as soon as possible, you can normally take script changes and run them without recompiling but not always, depends on what they're doing and whether they've had backend dependency code, etc.

I set up using Dilvish's suggested method of building on Linux that gives my compiled version direct access to my github clone, which works well for me and as I assume most Linux users do similar now it's probably common, when I was on Windows I did similar to you but we didn't have PErsistent Config back then so you had to manually edit each week.

**Comment by MatGB** [comment]
Right, I think I've caught everything, assigned everything and got it, mostly, balanced. It needs feedback but closing this now.
[Prioritised and balanced research and production bonuses](https://github.com/freeorion/freeorion/commit/5770d829b7be94a6cfaac83c89b98e64833a73c2)
