### ISSUE TITLE
Import AI code only after freeOrionAIInterface is ready

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#606]
We initialize python in 2 stages:

```
- import code (which execute some code like config creation)
- prepare AI in c++ code and call `initFreeOrionAI`
```

Can we prepare AI first and only after that import python libs? 
This will make `initFreeOrionAI` obsolete and make things less complicated.

**Comment by Vezzra** [comment]
Thx!

**Comment by Cjkjvfnby** [comment]
ping

**Comment by Vezzra** [comment]
Ok, I've squeezed in a quick look at the initialization code sections. I've to admit that I'm not sure what should be done differently - what exactly is this "prepare AI in C++ code" you're referring to, that should happen before the import of the `FreeOrion.py` module?

Because there isn't really happening much in terms of "preparing the AI" after the import of `FreeOrion.py` which could be done before that import. The import is actually one of the last things happening after everything else has been initialized. The only thing that does some kind of AI preparation after `FreeOrion.py` has been imported is the call to `initFreeOrionAI` - and that call of course requires the `FreeOrion.py` to be imported, otherwise it can't be called (as it's defined in `FreeOrion.py`).

So, I'm a bit confused about what exactly you want me to do...?

**Comment by Cjkjvfnby** [comment]
If you put `print fo.empireID()` to module code or `initFreeOrionAI` you will get `-1`, in generateOrders you will get real number.

I was wrong assuming that this value is already set when `initFreeOrionAI` called.

I want `empireId` and other constants were accessible at the moment of import.

**Comment by Vezzra** [comment]
Ah, now I understand what you are getting at.

> I want empireId and other constants were accessible at the moment of import.

I'm sorry, but that is not possible. The way the AI client is designed and implemented, the initialization and import of the `FreeOrionAI.py` module has to happen when the client _application_ is initialized, _before_ the game is started/loaded. At that stage no game specific data (like empire id and the other constants you're referring to) is available, simply because game initialization happens in a separate step _after_ the client app has been initialized. That can't be done differently, it's not possible to start/load the game before the Python AI has been initialized.

The purpose of `initFreeOrionAI` is to provide a function where AI scripters can run optional game independent initialization code. Any initialization code that requires access to game specific data has to happen in `startNewGame` (called in case a new game is being started) and `resumeLoadedGame` (called in case a saved game is being loaded).

**Comment by Cjkjvfnby** [comment]
Got you. Lets close this issue.
