### ISSUE TITLE
universe.getObject should not be used in AI code

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#664]
For all objects we have specified getters: `getBuilding`, `getFleet`, etc. Using proper getter make code more readable. `getObject` must go away.

TODO:
- [x] replace usages with correct getters
- [ ] remove `getObject` python binding. @Vezzra I need your approve before start this step

**Comment by Vezzra** [comment]
Well, that's actually a change I'm not comfortable going ahead with without hearing @Dilvish-fo on it - @Dilvish-fo, can you chime in on this one?

Personally I'm a bit wary - what if you want to iterate over all universe objects contained e.g. in a system? There a generic universe object getter might come in handy, and make things unnecessary difficult if we remove it.

Of course I don't know if that's a even remotely realistic use case for the AI scripts. I can however imagine that this might be useful for the turn event scripts... on the other hand, we can of course remove it now, and if it should be needed at some point we can always add it back in.

What do the others think?

**Comment by LGM-Doyle** [comment]
@Vezzra the get_objects is used by the server during specials placement of the galaxy generation, where the objects are treated simply as their base class, just objects, not a particular child class.

@Cjkjvfnby I agree with the code changes that you made in #666 where you replaced generic getObject with getBuilding because you knew beforehand that you wanted a building.

However, I think getObject should remain for the cases where a condition/effect is applied all objects regardless of type.  There may be none of these cases in the AI code.

It is easy enough to add/remove wrapper functions if you are compiling from source and you know where to look.  However, can python only hackers work around its absence?

**Comment by Cjkjvfnby** [comment]
> However, I think getObject should remain for the cases where a condition/effect is applied all objects regardless of type. There may be none of these cases in the AI code.

And such cases in Ai code will be complicated. 

> It is easy enough to add/remove wrapper functions if you are compiling from source and you know where to look. However, can python only hackers work around its absence? 

I don't sure that I understand what you ask me.

I can add/remove function in python, example of adding new method to system [object](https://github.com/freeorion/freeorion/blob/master/default/AI/freeorion_debug/extend_free_orion_AI_interface.py#L76)

`universe.allObjectIDs` [->](https://github.com/freeorion/freeorion/blob/master/default/AI/freeorion_debug/ide_tools/result/freeOrionAIInterface.py#L1969) can be replaced with other getters.  So It is possible to collect all IDs and convert them to objects without `getObject`.

**Comment by LGM-Doyle** [comment]
Since you pointed out that `universe.allObjectsIDs` can be converted to `Objects`  that addresses my concern.

I explained poorly.  I will try a different way.

Generic code using the base class handles changes in the class system without any re-work to the code.

For example, if freeorion added Satellites/Moons as a subclass of `Object` the specials placing code would work without any changes.

I was concerned that removing `getObject` would force python only AI programmers to process `Object`s with an inefficient and less maintainable `if else then` tree style of code.

**Comment by Cjkjvfnby** [comment]
If new object will be added, python only coders will wait for build.

`getObject` does not return instance of `UniverseObject`. It returns one of classes, that inherited form  `UniverseOBject`.  So this class must be defined in python interface or you will get exception.

**Comment by Vezzra** [comment]
@Dilvish-fo, as you seem to slowly get back into things, can you comment on this proposal?

**Comment by Morlic-fo** [comment]
I prefer

```
class ThreatMap(object):
    ...
    def get_location():
        return fo.getUniverse().getObject(self.id).systemID
```

over

```
class ThreatMap(object):
    ...
    def get_object():
        raise NotImplementedError
    
    def get_location():
        return self.get_object().systemID

class ShipThreatMap(ThreatMap):
    def get_object():
        return fo.getUniverse().getShip(self.id)

class PlanetThreatMap(ThreatMap):
    def get_object():
        return fo.getUniverse().getPlanet(self.id)
```

**Comment by Cjkjvfnby** [comment]
@Morlic-fo, on one hand you save some LOC by removing simple code (easy to understand, hard to make error) for other hand you allow developer to write bad code (it was in AI and same pattern was fixed in C++ part couple of weeks ago).

**Comment by Morlic-fo** [comment]
> you allow developer to write bad code

Then let's not allow the bad code to be merged. Simply refuse any PR which uses ```getObject``` where a more specialized function could be used instead. 

No reason to remove it from the interface if there are scenarios where it can be useful.
