### ISSUE TITLE
Nanorobotic Processing Unit enabled by two dependent techs

### ISSUE THREAD

**Issue by Assargadon** [freeorion/freeorion#782]
**Nanorobotic Processing Unit** is enabled by both **Mid-Combat Logistics** and **Nanorobotic Maintenance**. But first one is dependent on second one, i.e. you cannot reach **Mid-Combat Logistics** before **Nanorobotic Maintenance**, so you'll already have **Nanorobotic Processing Unit** enabled anyway.

**Comment by dbenage-cx** [comment]
Guessing this is an older build? Relevant commit: 793b642a

**Comment by MatGB** [comment]
Good catch, when I got the email on my phone I worried I'd missed one. 

@Assargadon, it was a holdover from the time when the tech tree and prerequisites weren't fairly settled, recent code changes made it a lot easier to find them all so it's fixed in Trunk already, thanks for reporting it though, fixing it had been creeping up my to do list for ages.
