### ISSUE TITLE
comsats are too cheap and too effective

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#828]
Each comsat causes planet to fire upon attackers (and attackers hit comsats, not planet).

Some dozens of cheaply-produced comsats can overcome very large fleets (even fleet's weapons don't matter since comsats have low health and damage is wasted)

**Comment by MatGB** [comment]
> Each comsat causes planet to fire upon attackers

Incorrect. Planets will fire on _attackers_ regardless. Comsats set to aggressive will initiate a combat even if enemy ships in system are set to passive (eg: scouts). Comsats are completely unnecessary for defence against an aggressive fleet.

> Some dozens of cheaply-produced

A player using _dozens_ of comsats is going to suffer due to fleet upkeep making all their ships more expensive. Planetary Defences are meant to be a threat in the mid to late game, comsats represent the confusion of battle and similar, you need bigger/better fleets to take well defended systems.

Regardless, Comsats will be reduced in effectiveness over the next release cycle as Fighters and Flak weapons are introduced and we hope to eliminate the need for them with UI tweaks at some point.

Given that all they are is the Base hull with no slots, and we deliberately increased the build time of that recently, I'm going to close this issue.

**Comment by l29ah** [comment]
afair, comsat price is not affected by upkeep

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by afwbkbc** [comment]
Is it intended that fleet shoots comsats instead of planet defences? That way one player can have 4 times higher industry, but he will never be able to capture a star with single planet (200/90) of another player which builds comsats and nothing else. And what if he has 4 planets in system? Then first player must have even more industry. This is ridiculous. Moreover, for this comsat-defence "strategy" to work you don't even have to research any weapons, just max up planetary defence techs and pump comsats. then you will be invincible. such bullshit omg

**Comment by afwbkbc** [comment]
MatGB: did you understand the issue? It's not that comsats help planets attack, but that fleets attack comsats instead of planet, while planet attacks and destroys them. So comsats = additional planet armor.

**Comment by Voker57** [comment]
Comsats have insanely high HP/pp rate (7 with all relevant tech) and fleet upkeep does not affect them, so while it cripples your fleet capacity, planets can gain nigh-invulnerable comsat shields.

Also, build time is largely irrelevant since with 1pp cost you can crank out hundreds of them per 3 turns.

**Comment by MatGB** [comment]
Give me a savegame where this has been done. Demonstrate that it's an effective strategy.

Because I've never seen this plus in order for it to work you have to have the planet on Defend focus which means you're not doing anything else. 

It might create a speedbump that's hard to attack but it isn't going to stop you from going around it and taking the rest of the galaxy, at which point you can build a fleet more than capable of taking out an large number of comsats.

**Comment by afwbkbc** [comment]
@MatGB this is the save, I think - http://dump.bitcheese.net/files/fypunuk/FreeOrion_L29Ah_L29Ah_0179_20160802_003444.mps
You can see my fleet stationed near his border at the top of the map.
He has tons of comsats.
During attack, I lost almost all of my fleet, which was MUCH more expensive to build. "a speedbump that's hard to attack" - not hard, but impossible, if he chooses to pump comsats non-stop. The best I can do is build ships with 6 external slots with Laser 2 in them, but even this will be more expensive than comsats. There are nothing else to be done.
I still don't understand why don't ships target planet and other dangerous targets first and instead target harmless comsats. I think this is the main issue to be fixed.

**Comment by MatGB** [comment]
What version are you playing? I'll need to compile the game based on that string (I'm on Linux).

Also, you say "Laser 2", does this mean you're using a version old enough to not have the weapon refinement changes?

Edit: it's OK, the version is in the header of the save file, I always forget that.

**Comment by afwbkbc** [comment]
@MatGB version is 2016-07-26.ba59cf7

**Comment by MatGB** [comment]
OK, bit of messing around, had to switch player, but the fleet you have there took out all the comsats and the planetary defences.

Most of it then died horribly to mines, as will the massive stack of unarmoured troop ships also sat there. Personally I'd have sat that stack out and gone to conquer/defend much of the rest of the galaxy while I researched basic essential techs like reinforced hull, armour, etc.

A target priority system has been discussed however invading systems is meant to be hard, you're meant to take losses, and the defender is meant to have some sort of advantage. That space is full of junk that gets in the way, especially in and around defended core systems, is fine.

Dump the "tactical missile" ships, they're no good against defended systems, stop building any ship with structure below 20 as mines will kill them, use some shields and put armour on your ships. Oh, and research stuff like Orbital Habitation, Xenological Genetics and similar to get the significant population (And therefore production) boosts that they need.

Seriously, your fleet mostly died in the attack I launched, but that wasn't due to the comsats, the mines are the big problem and that's only a threat due to the ship designs.
![mine-damage-nj](https://cloud.githubusercontent.com/assets/11533206/17340847/da34da8c-58e9-11e6-9c57-8a0a8253e25f.png)

**Comment by afwbkbc** [comment]
Ships attacking comsats instead of planet is still a bug, no? Just look how fast can he rebuild comsats. And that is when he is very behind in industry.

**Comment by afwbkbc** [comment]
What if he builds total of 10k structure of comsats on system with 4 planets? What fleet will I need to break it?

**Comment by MatGB** [comment]
No, it's not a bug, it's part of the current design intent that combat is meant to be chaotic.

In fact, in the next Release we're introducing fighters, one type of which is purely defensive and acts in the exact same way as comsats currently do.

And to answer your second question, a good, high tech one, a bunch of fractals, heavy asteroid or titans with decent structure should wade through it.

**Comment by afwbkbc** [comment]
It's not chaotic, comsats are always targeted first and planet last. I don't see any sense behind it. How would it work in real life?

**Comment by MatGB** [comment]
Comsats are not always targetted first. Categorically know that to be false. Each shot is random amongst all available targets, if there are a lot of comsats each has equal chance of being targetted but en masse they make the planet less likely to be targetted.

And we don't care about "real life" as we simply cannot know, it's a space based game with FTL travel and talking vines.

**Comment by afwbkbc** [comment]
@MatGB not a single shot was made to planet until at least one comsat remained.

**Comment by MatGB** [comment]
I just reran that turn, I had two hits on the planet in the first round, in the second round multiple comsats were still there. It's random. It's provably random, designed to be random and works randomly. 

Targeting is one of the very few elements of the game that is fully random and I've not seen any evidence here or before that it's anything other than random. 

In a battle where there are over 60 comsats and one planet with 3 other targets (the "Fat Boy" design), then each shot in the first round has a 60/64 chance of hitting a comsat.  In teh second round in my test there were only 16 comsats left so it went down to 16/20 and in the final round there were only combatants, but in each round the planet and aggressive ships were also hit.

Regardless, there is no bug here, if there needs to be a discussion about design intent and/or balancing, it needs to be where everyone will see it (ie the forum). 

I rarely if ever build comsats, I have on occasions found a use but I'd rather build a cheap corvette. Your opponent has found a way to slow you down while they try to catch up on your tech/production advance, your ship designs and fleet is particularly vulnerable to this method in a way that a more balanced design using armour would not be.

**Comment by afwbkbc** [comment]
Ok, so if there are 200 comsats than chance to hit planet is like 0.5%. Wow. 200 hp is 1.4k hp, and fleet must survive for multiple turns, I'm really sure that comsats built for that purpose were several times cheaper (and easier to rebuild). It's not that he just slowed me down, it's more like he stopped me, because I need much more industry to attack than he to defend.

**Comment by MatGB** [comment]
Hasn't stopped me, I've captured Situla and Haedi alpha, have decided to box in the homeworld while I rebuild/expand elsewhere and am in the process of liberating the Terminus system from Blue, took me awhile to work out you were at peace with them but now I've cancelled that it's all good and I'm about to take two Eaxaw shipyards. 

That, combined with the tech I've researched, will make eventually taking out residual green a walkover.

**Comment by MatGB** [comment]
Oh, turn 199 now

**Comment by afwbkbc** [comment]
@MatGB was green player building comsats on Situla non-stop?

**Comment by MatGB** [comment]
Hard to say, another cropped up before my troop ships arrived but I took it in a small number of turns, just had to wait for your robo-hull troop ships to get there.

Regardless, you're looking at the situation entirely from your side and your specific tactical objective. From the perspective of Green, all the comsats are doing is slowing/stopping you, and not doing a great job of that.

But while they're not subject to upkeep, all other ships are, meaning that the 20 comsats at Berkano and the 99 at Heliconia are pushing up the costs of all other ships build, especially combat ships, by 120%—on the other hand, I have less than 40 ships and I'm fighting against three AIs with them. Pushing out while my tech catches up with what I need to break through the Helliconian defences will take a bit but not too long now, in the meantime I've expanded my territory substantially in other directions.

100+ comsats when you're beseiged and about to lose means almost zero ability to build new actual combat ships. The green AI is toast regardless of whether it's building more comsats, which I doubt, most of what I've seen is a fairly standard AI 'manticore' design.

**Comment by afwbkbc** [comment]
Idk, maybe you're just lucky :)

**Comment by Vezzra** [comment]
Pls, guys, discussions like this belong on the forum. You're welcome to continue there 😃

**Comment by afwbkbc** [comment]
Maybe comsats should be renamed to 'planetary hull' or something then.

**Comment by adrianbroher** [comment]
The issue tracker is not our forum.
