### ISSUE TITLE
Fortress mines kill defending Sentinel

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#873]
The Fortress special generates a Guard to prevent early conquest at start of game, but the mines affect slowly kills said sentinel.

This isn't an instant fix as we now have all the mine effects using a macro, a short term hack could stop all mines from hurting sentinel, sentry, maintenance ship and warden designs. Alternatively the mines affect could be turned off unless the special is owned. I'm not sure on the ideal longer term solution.

**Comment by dbenage-cx** [comment]
My initial intention was to treat unowned planets as the same empire as unowned ships (re: mines), and try to limit the number of effectsgroups.
I have a [potential fix](https://github.com/dbenage-cx/freeorion/tree/fix-873_mines_unowned_source_target) to restore the intended scope.  I need to test all the other possible mine scenarios before PR.

Is immunity only for the guard ships preferred over all unowned ships?
If so, are these 4 the only ship designs? (since designs can not have tags, will likely stick the list in a macro)

**Comment by MatGB** [comment]
They're, currently, the only 'guard' ships, and they all use a variant of the guard hulls—IIRC hulls can have tags and it might be better to tag them as it can be used in other effects.

I think it would also make sense to exclude the Drone Factory, simply as it's also a stationary thing and it makes little sense for an ancient thing to suddenly start being destroyed by mines at the start of the game. I think it's better if wandering monsters do get hit by them, but that's a personal preference, having unowned stuff be immune might be a better/easier fix. It doesn't make a difference, really, for balance, but it does for realism/breaking disbelief and I'm not sure the best way.

**Comment by Vezzra** [comment]
I guess @MatGB is on the right path here. Just put a tag on all space monster hulls you want to be immune to mines, and in the scope clause of the mine effect test for that tag. Sounds like the simplest and most flexible solution to me.
