### ISSUE TITLE
Singleplayer freeoriond opens socket with INADDR_ANY triggering firewalls

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#874]
### Environment

- **FreeOrion Version**: master
- **Operating System**: any
- **Graphic card used**: -
- **Fetched as**
  - Compiled from source
### Description

As reported with #872 `freeoriond` seems to trigger various Desktop Firewalls to ask for permission when opening a network connection, even when the user only plays a single player game.  Unaware users may block this (why should a single player game require 'internet access' anyway?) and are unable to play any single player game unless the application is removed from the firewall blacklist.
### Expected Result

User is never pestered with any Firewall permission query when starting a single player game.
#### Steps to reproduce

Prerequisites:
- Have a running firewall without a freeoriond whitelist entry.

Steps:
- Run freeorion.
- Do a `Quick Start` game.
- Firewall asks user if `freeoriond` should be allowed to have a network connection.
- Deny network connection for `freeoriond`.
- User can't play any game now or in the future because `freeoriond` is denied to create a network connection.

**Comment by adrianbroher** [comment]
Milestone: I suggest this should be part of release 0.4.6

The issues affects pretty much every clueless Windows user with a firewall and breaking the game by pressing the wrong button is pretty severe.

@Vezzra any opinion on that?

**Comment by MatGB** [comment]
If it can be fixed by someone very soon, I'd agree, but I wouldn't want it release blocking personally, we've been living with it for years and I always found it a mild annoyance on Windows that was easily solved by simply whitelisting it the first time asked.

Basically, if it's either easy to do or you're able to do it fairly quickly, it should go in but shouldn't block if it takes longer.

**Comment by adrianbroher** [comment]
> we've been living with it for years

You don't know how many potential players we scared away with that. I don't know either, but I hope I made my point clear. This is a very negative first time use experience.

**Comment by MatGB** [comment]
Oh, I agree completely. But we're already way behind on Release, if you can do it, great, it needs to go in as soon as it can, but I don't think it should be release blocking if you can't.

**Comment by Vezzra** [comment]
I agree with @adrianbroher on that - this is a quite serious issue actually, and if we can, we should address it. So I'm going to flag this one for the 0.4.6 release for now.

However, I also agree with @MatGB, that if this can't be addressed fairly quickly/easily, then we shouldn't block the release because of it. We've lived since forever with that issue, we'll survive one more release with it. 😉

**Comment by adrianbroher** [comment]
@Vezzra

I've seen the response as email, but it isn't displayed here. Was this intended?

> I agree with @adrianbroher on that - this is a quite serious issue actually, and if we can, we should  address it. So I'm going to flag this one for the 0.4.6 release for now.
>
> However, I also agree with @MatGB, that if this can't be addressed fairly quickly/easily, then we shouldn't block the release because of it. We've lived since forever with that issue, we'll survive one more release with it. 😉

**Comment by Vezzra** [comment]
No, this certainly was NOT intended. What's strange is that I can see
_my_ post just fine, but I can't see _yours_ - I only received an email,
just like you did with my post. This applies wether I'm logged in or
not, so it apparently has nothing to do with my account.

And I'm writing this response as a direct reply to your email, not via
the github web frontend (because I can't see your post).

It's the same with the other two replies (to the other two issues) you
apparently only saw as emails. I can see my posts, but can't see your
replies (logged in or not).

Although a very strange thing happened just before when I opened two new
issues: suddenly a red insert appeared on every github page I opened,
stating that my profile has been hidden because some "robot" flagged me
as potentially not human, and a request to contact github support (which
I did).

So either something went awry with my account (but why do I see my posts
and not yours even if I'm not logged in?), or there is something strange
going on with the github site currently...

**Comment by adrianbroher** [comment]
Nevermind the ruckus, the github webgui bugged out for me. Reloading the page fixed it.

>  I can see my posts, but can't see your replies (logged in or not).

Yeah, I deleted them afterward reloading the page and seeing your posts. :o)

**Comment by Vezzra** [comment]
@adrianbroher: Ah, ok, that explains why I _still_ can't see them, was starting to get really worried now.

Just to be sure: I've seen your reply to #877, so you definitely can see that, I assume you can see #876 too, right?

**Comment by adrianbroher** [comment]
> Just to be sure: I've seen your reply to #877, so you definitely can see that, I assume you can see #876 too, right?

Yeah, I can see the opening post of #876.

> Although a very strange thing happened just before when I opened two new
> issues: suddenly a red insert appeared on every github page I opened,
> stating that my profile has been hidden because some "robot" flagged me
> as potentially not human, and a request to contact github support (which
> I did).

It seems like some people on the interwebs had this problem too and some comments/PRs and other things were not visible during the time but I can't say for sure.

https://www.reddit.com/r/github/comments/4a42w6/user_profile_flagged_with_no_explanation/
https://github.com/jcabi/jcabi-github/issues/940
https://github.com/HoTT/book/issues/282
https://podbay.net/posts/84256

**Comment by Vezzra** [comment]
Yep, that's apparently exactly what happened here. Fortunately github support reacted lightning fast and restored my account/profile within minutes, so that's why my posts came up once you reloaded.

So, as annoying as that has been, I certainly won't complain about their reaction time. That's a big thumbs up! 👍 😃
