### ISSUE TITLE
Gateway to the Void produces supply

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#955]
And prevents the other player's supply to go through the system: ![screenshot](https://dump.bitcheese.net/files/dipehap/2016-09-07-212811_1270x757_scrot.png)

**Comment by Vezzra** [comment]
Producing supply is a bug IMO, but blocking enemy supply I consider as expected behaviour. No supply should be able to propagate through a Gateway to the Void system.

Should be easy to fix though, just adding an effect that sets supply of all planets to 0, so I'm tagging this for the release.

**Comment by l29ah** [comment]
Well, it's strange that ships can get over it and supply cannot (should not).

**Comment by Vezzra** [comment]
Hm, setting supply of all planets _in_ the Gateway to the Void system to 0 won't prevent supply from your own colonies nearby propagating through that system, so that would be consistent with ships being able to pass through it. It would just prevent the system from being a suppy source itself, which is the main concern of your issue here.

Then it's just enemy supply that gets blocked, but that's not different from any system where you have colonies or outposts in. As long as your enemy has no armed forces in such a system, it will block enemy supply (that's an adjustment which recently went in because the AI hasn't been updated to deal with that mechanic yet).
