### ISSUE TITLE
Ghost cursor remains when moving mouse pointer out of window

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#963]
### Environment
- **FreeOrion Version**: 2016-09-09.3058052 (RC1 0.4.6)
- **Operating System**: Windows 7
- **Graphic card used**: GT520M
- **Fetched as**   \* Weekly development build
### Description

When moving the mouse out of the Freeorion window, a ghost mouse pointer keeps being drawn where the window was left:

![test](https://cloud.githubusercontent.com/assets/11706951/18409580/87c10eb8-774a-11e6-8d13-8fd8fc546000.png)

Notice the two mouse pointers.

The ghost pointer remains until the window loses focus or the mouse is moved into the window again. If the mouse pointer is moved through the window while out of focus, there will be a ghost pointer left behind again.
### Expected Result

Mouse pointer isn't drawn when mouse pointer is out of the window.
### Steps to reproduce
- Start Freeorion in Windowed mode
- Move Mouse pointer out of game screen

**Comment by geoffthemedio** [comment]
Is this really a problem / bug?

**Comment by Morlic-fo** [comment]
Is it a "problem" - not really. Is it of any importance? Not really.

Is it a (minor) graphical issue? I'd say so...

**Comment by Vezzra** [comment]
It's not perfect, it would be better if the SDL mouse pointer would disappear once you move the mouse outside the FO window, but that issue had been there since forever, I never gave it much attention.

Can that be solved at all? I always thought this is a consequence of actually having a second mouse cursor drawn and controlled by the SDL framework (something that occasionally becomes more obvious when the system mouse cursor doesn't get "switched off" when entering the FO window, and suddenly you have two cursors, one always trailing slightly behind the other) which can't be really avoided...
