### ISSUE TITLE
Unable to leave 'Credits' menu

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#966]
### Environment

- **FreeOrion Version**: v0.4.6+ [build 2016-09-10.9c26ef7] CMake
- **Operating System**: Linux
- **Graphic card used**: -
- **Fetched as**
  - Compiled from source
### Description

When clicking on the 'Credits' intro menu button the credits start to roll.  But the user has no clear indication on how to leave the credits.  Neither `LMB`, `RMB`, `Space` or `Enter` stop the credits.  Pressing `Escape` terminates the whole game immediately.
### Expected Result

- Having a text note in a corner, which indicates a key or mouse button to leave the credits.
- When pressing the respective control the UI should display the intro menu again.
- When pressing the `Escape` key the application shouldn't close abruptly (it gives me that 'oh, FO crashed' feeling) but return to the intro menu.
### Steps to reproduce

- Be in Intro menu.
- Click `Credits`.

_either_
- Press LMB, RMB, Space, Enter.
- Credits still roll.

_or_
- Press Escape.
- Application terminates.

**Comment by geoffthemedio** [comment]
Why is pressing escape causing the program to exit for you? Doesn't do that for me on Windows...

**Comment by Ouaz** [comment]
v0.4.6 [build 2016-09-04.22b124c] 
-pre-RC1-

When launching the credits, everything is darkened (background, main menu panel) like everything become unactive as the credits roll. Even if the effect is nice, it's quite misleading for the user, because  **the main menu panel is actually still active during the credits.** 

It's possible to click on any button (clicking on "Credits" closes the Credits, on "Single Player" closes the Credits and opens the Galaxy Setup, etc.).

It also explains why pressing "Escape" during the credits closes directly FO. ^^ (Note to Geoff: I'm on W7, and I have the same behavior than adrian, that's weird pressing "Escape" during the credits doesn't close FO for you...)

One possible fix is just to remove the fading effect, and it will become obvious than the main menu panel is still active.

**Comment by adrianbroher** [comment]
> Doesn't do that for me on Windows...

So it's platform specific?

Does LMB work for you, @geoffthemedio? Because according to the code it should.

@Ouaz, you do use a mac right? So it happens on Linux and Mac but not on Windows?

> **It's possible to click on any button (clicking on "Credits" closes the Credits, on "Single Player" closes the Credits and opens the Galaxy Setup, etc.).
> 
> It also explains why pressing "Escape" during the credits closes directly FO. ^^**

Good catch, I didn't notice that.

> One possible fix is just to remove the fading effect, and it will be obvious than the main menu panel is still active.

That would solve the the need for a dedicated button and a label but I don't know if I would like the visual  outcome, testing…

**Comment by geoffthemedio** [comment]
Escape works, but only after left-clicking on the scrolling credits.

**Comment by dbenage-cx** [comment]
Place the fade behind the menu screen?

Suspect if thereis a difference, it is window manager/setting specific, not strictly OS.
I use a select on hover setting (allows typing into the window with the pointer over it).
If I focus another window and then defocus it, `esc` has no effect on credits screen.  Actively clicking on the client window will then register a subsequent `esc` press.
This is the same behavior when first starting the client (need to actively select it before `esc` registers.

**Comment by adrianbroher** [comment]
The IntroWindow is not modal, but I don't see a reason why it shouldn't.

I changed it to be modal, closing on LClick and KEY_ESCAPE and made its instance local to the OnCredits functions.  @geoffthemedio could you check if the fix works for you (PR #968)?

**Comment by Vezzra** [comment]
This means of course that we will have a RC2.
