### ISSUE TITLE
Drydocks on outposts trigger "Can't repair due to low happiness" sitreps

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#970]
### Environment
- **FreeOrion Version**: 0.4.6 RC1
- **Operating System**: any
- **Fetched as**
  - Binary release
### Description

When the population of a colony with a drydock drops to zero (for whatever reason, in my case because I CC'ed it), an outpost with a drydock is left. If you park damaged ships at that outpost, you will get sitreps telling you that these ships can't be repaired due to low happiness (most likely due to the fact that the happiness meter of outposts is zero).
### Expected Result

Drydocks left on colonies that got reduced to outposts should not be able to do repairs anyway, so those sitreps should not show up at all.
### Steps to reproduce
- Well, park some damaged ships at an outpost with a drydock.
- Enjoy the sitreps. 😉

**Comment by MatGB** [comment]
Feature, not bug. The point of the sitreps is to ensure players know their ships sent for repair aren't going to get fixed where they are.

**Comment by Vezzra** [comment]
That's true for cases where the player expects their ships getting repaired, so if anything prevents that the player has to be informed of course. But in this case I don't think a player expects that (drydocks can't be built on outposts after all), so there is no need to inform them that no repairs occurred.

But even if, the sitrep you get is still confusing, especially since outposts don't display the happiness meter (in absence of a species). At the very least we'd have to display a different sitrep, something like "At <system>: drydock could not do any repairs because planet has been depopulated".

Personally I'd prefer the no sitrep option, because this sitrep gets triggered for each single ship, which can amount to quite large numbers of not really needed messages later in the game. Of course you can filter them, but what's the point in having a sitrep hardly anyone will ever miss?

Do you really think it's necessary to have a sitrep for this case?

**Comment by MatGB** [comment]
I think the sitrep is necessary as most of this group of sitreps is there to help newer players learn the game.

Having a drydock for repairs is a significant thing, and sometimes planets depopulate due to really daft decisions: while we've got the "no population left" sitrep fixed for the most part, there are going to be edge cases (eg a Chato world converted to a black hole) and/or evacuations/CCs that weren't intended to empty a world.

The point is for players to know that repairs won't happen where they are, so that, for example, you move the fleet somewhere else. Generally the sitreps happen right at the end of the sitrep list so I, personally, don't find them annoying even though I rarely personally care about the no-happiness stuff. If you want to change it so it's a different sitrep I care not, but I do think a sitrep is needed, they're not there for either of us.

**Comment by Vezzra** [comment]
Alright - shouldn't be hard to adjust the PR...
